README.md
docs/run-book/01-deployment.md

fix storage provider readme.md.
N/A
N/A
N/A

docs: fix error of README.md

---

README.md
docs/run-book/01-deployment.md
model/const.go
pkg/p2p/node.go
pkg/p2p/node_config.go
pkg/p2p/node_config_test.go
store/sqldb/store.go

Support DNS for p2p bootstrap node
Use for k8s ALB and NLB
N/A
N/A

feat: support dns for p2p node

---

service/tasknode/replicate_object_task.go
store/sqldb/traffic.go

Fix multi update map bug and polish db error.
N/A.
N/A.
* TaskNode/SQLDB.

fix: fix multi update map bug and polish db error

---

go.mod
go.sum
service/blocksyncer/block_syncer_indexer.go

feat: add txhash when export events

---

README.md
config/config.go
service/gateway/request_util_test.go
test/e2e/localup_env/greenfield_sp_env/sp0/config.toml
test/e2e/localup_env/greenfield_sp_env/sp1/config.toml
test/e2e/localup_env/greenfield_sp_env/sp2/config.toml
test/e2e/localup_env/greenfield_sp_env/sp3/config.toml
test/e2e/localup_env/greenfield_sp_env/sp4/config.toml
test/e2e/localup_env/greenfield_sp_env/sp5/config.toml
test/e2e/localup_env/greenfield_sp_env/sp6/config.toml

Refine tests and docs.
N/A.
N/A.
* Tests/Docs.

chore: polish tests and docs

---

.github/workflows/e2e-test.yml

The integration test command was not updated and it was not executed
NA
NA
* NA

fix: integration test

---

util/grpc/retry.go

Adjust rpc timeout time.
N/A
N/A
N/A

fix: delete rpc timeout time

---

model/const.go
service/gateway/object_handler.go

Fix universal endpoint download as attachment 
For frontend correct download purpose 
Universal endpoint return ContentDispositionHeader as attachment 
* Downloader

fix: universal endpoint attachment

---

.github/workflows/e2e-test.yml
config/config.go
config/config_template.toml
config/subconfig.go
go.mod
go.sum
pkg/middleware/http/ratelimiter.go
service/gateway/gateway.go
service/gateway/gateway_config.go
service/gateway/router.go
test/e2e/localup_env/greenfield_sp_env/sp0/config.toml
test/e2e/localup_env/greenfield_sp_env/sp1/config.toml
test/e2e/localup_env/greenfield_sp_env/sp2/config.toml
test/e2e/localup_env/greenfield_sp_env/sp3/config.toml
test/e2e/localup_env/greenfield_sp_env/sp4/config.toml
test/e2e/localup_env/greenfield_sp_env/sp5/config.toml
test/e2e/localup_env/greenfield_sp_env/sp6/config.toml

gateway rate limit function added
Add the traffic limiting function to each interface to ensure service stability
N/A
add new config
add new file rate_limiter.go

feat: add rate limiter function in gateway

---

pkg/metrics/metric_items.go
pkg/metrics/metrics.go
service/downloader/downloader_service.go
service/gateway/request_util.go
util/grpc/metrics.go

Support authv2 bucket-quota API.
authv2 is just for js-sdk testing and will be removed in the future.
N/A
* Gateway.

fix: support authv2 bucket-quota api

---

service/gateway/object_handler.go

Put universal endpoint response header in the correct place in code 
N/A
N/A
* Downloader Universal Endpoint update

fix: put universal endpoint response header in right place

---

README.md

Update readme the links of docs.
N/A
N/A
N/A

fix: update readme docs used links

---

service/signer/client/gnfd_sign_client.go
service/signer/client/gnfd_sign_client_test.go

send sealObject tx by async mode to improve performance.
n/a
n/a
* signer

feat: signer async send sealObject tx

---

service/gateway/client/gateway_client.go
service/tasknode/replicate_object_task.go

Cross region network opt
N/A
N/A
N/A

fix: cross region network opt

---

README.md
go.mod
go.sum

upgrade greenfield version to v0.2.0
N/A
N/A
N/A

fix: upgrade greenfield version to v0.2.0

---

CHANGELOG.md

Add v0.2.0 changelog
N/A
N/A
N/A

docs: add v0.2.0 changelog

---

config/config_template.toml
model/errors/rpc_error.go
service/signer/client/gnfd_sign_client.go
service/stopserving/stopserving.go

Refine codes of stop serving and add more logs.
Refinement
NA
* NA

fix: fix deprecated broadcast mode

---

go.mod
go.sum
service/metadata/service/object.go
store/bsdb/object.go

fix: data query issues caused by character set replacement
N/A
N/A
* fix the query sql
* fix potential array index goes out of bounds bug

fix: data query issues caused by character set replacement

---

config/subconfig.go

Fix the config used by stop serving.
Bug fix
NA
* Na

fix: fix config reading of stop serving

---

service/signer/client/gnfd_sign_client.go
service/stopserving/stopserving.go

Cache nonce locally to speed up discontinue transactions.
Save gc nonce locally
NA
* signer

feat: cache nonce for sp gc account

---

go.mod
go.sum

fix:statement policy id

---

go.mod
go.sum

fix:blocksyncer statement policy id

---

go.mod
go.sum

fix:blocksyncer oom

---

service/auth/auth_service.go
service/auth/auth_service_test.go

apply expiry date for user public key 
The user public key should be disabled when the expire date becomes past. 
UT

fix: apply user public key expiry date

---

store/bsdb/common.go
store/bsdb/object.go

fix listobjects sql error
N/A
N/A
* update listobjects sql

fix: listobjects sql

---

service/manager/gc_worker.go

Fix GC worker bug.
N/A.
N/A.
* manager: gc_worker.

fix: fix gc worker bug

---

service/manager/gc_worker.go

Fix GC worker bug, cherry picked from https://github.com/bnb-chain/greenfield-storage-provider/pull/455.
N/A.
N/A.
* manager: gc_worker.

fix: fix gc worker bug (#455)

---

go.mod
go.sum

fix: update go.mod

---

base/gfspapp/app_options.go
base/gfspapp/approval_server.go
base/gfspapp/download_server.go
base/gfspapp/manage_server.go
core/module/null_modular.go

Fix the bug that approver and downloader misuse the receiver rcmgr, and add protection for nil module.
N/A
N/A
N/A

fix: base app rcmgr span panic

---

base/gfsptqueue/queue.go

Fix bug that delete task when call has, pop and top methods
N/A
N/A
N/A

fix: task queue gc delay when call has method

---

core/module/null_modular.go

Add error for cal nil model, some config error may call nil model, if return nil, it is diffcult to debug.
N/A
N/A
N/A

chore: add error for cal nil model

---

config/config_template.toml
config/subconfig.go
model/errors/rpc_error.go
service/signer/client/gnfd_sign_client.go
service/stopserving/stopserving.go

This pr cherry picks fixes and enhancement which had been applied in v0.2.0.
Bug fix
NA
* NA

fix: cherry pick fixes for stop serving 

---

modular/p2p/p2pnode/approval.go
pkg/metrics/metric_items.go
store/piecestore/client/piece_store_client.go

Fix sp metrics var name
N/A
N/A
N/A

fix: fix sp metrics var name

---

pkg/metrics/metric_items.go
store/piecestore/client/piece_store_client.go

Fix metrics error.
N/A
N/A
N/A

fix: metrics items name error

---

.github/workflows/e2e-test.yml
go.mod
go.sum

build: update e2e yml.
N/A.
N/A.
* update e2e  yml.

build: update e2e yml

---

base/types/gfsptask/download.go
core/task/null_task.go
core/task/task.go
modular/gater/admin_handler.go

Fix init challenge task add storage params for estimating limits.
N/A
N/A
N/A

fix: init challenge task add storage params

---

modular/downloader/downloade_task.go
modular/executor/execute_task.go
modular/signer/signer_client.go

Fix signer nonce less the chain nonce number and seal object retry.
N/A
N/A
N/A

fix: signer nonce less

---

base/types/gfsptask/gc.go
base/types/gfsptask/task.go
core/module/module_const.go
core/spdb/spdb.go
modular/executor/execute_task.go
modular/executor/executor.go
modular/manager/manage_task.go
modular/manager/manager.go
store/sqldb/gc_object.go

Refine gc object workflow, which is cherry picked from https://github.com/bnb-chain/greenfield-storage-provider/pull/493.
N/A.
N/A.
* executor/manager: gc-object task workflow.

fix: refine gc object workflow v0.2.1

---

base/types/gfsptask/gc.go
base/types/gfsptask/task.go
core/module/module_const.go
core/spdb/spdb.go
modular/executor/execute_task.go
modular/executor/executor.go
modular/manager/manage_task.go
modular/manager/manager.go
store/sqldb/gc_object.go

Refine gc object workflow.
N/A.
N/A.
* executor/manager: gc-object task workflow.

fix: refine gc object workflow

---

store/sqldb/sp.go

Refine sp db update interface.
Replace delete/insert to update, and ensure the transaction.
N/A.
* sp-db.

fix: refine sp db update interface

---

store/sqldb/sp.go

Refine sp db update interface which is cherry-picked from https://github.com/bnb-chain/greenfield-storage-provider/pull/503.
Replace delete/insert to update, and ensure the transaction.
N/A.
* sp-db.

fix: refine sp db update interface v0.2.1

---

modular/manager/manager.go
modular/manager/manager_options.go
modular/p2p/p2pnode/approval.go
modular/p2p/p2pnode/node.go

Add p2p log and sync sp info interval
N/A
N/A
N/A

chore: add p2p log and sync sp info interval

---

go.mod
go.sum
modular/p2p/p2pnode/approval.go
modular/p2p/p2pnode/node.go
modular/p2p/p2pnode/ping.go

Update p2p gogo protobuf lib to cosmos/gogo protobuf lib
N/A
N/A
N/A

fix: update p2p gogo protobuf lib to cosmos/gogo protobuf lib

---

.gitignore
store/piecestore/storage/b2.go
store/piecestore/storage/b2_test.go
store/piecestore/storage/const.go
store/piecestore/storage/object_storage.go
test/e2e/piecestore/b2_test.go

feat: support [b2](https://www.backblaze.com/b2/cloud-storage.html) as store
for sp store extension

feat: support b2 store

---

base/gfsptqueue/queue.go
base/gfsptqueue/queue_limit.go
base/gfsptqueue/queue_test.go

Add task queue ut.
N/A
N/A
N/A

test: add task queue ut

---

base/gnfd/gnfd_service.go
core/consensus/consensus.go
modular/executor/execute_task.go
modular/gater/admin_handler.go
modular/gater/object_handler.go

Query storage params by timestamp
N/A
N/A
N/A

feat: query storage params by timestamp

---

go.mod
go.sum

feat:group add extra field

---

base/gfspclient/metadata.go
modular/gater/const.go
modular/gater/errors.go
modular/gater/metadata_handler.go
modular/gater/router.go
modular/gater/router_test.go
modular/metadata/metadata_group_service.go
modular/metadata/metadata_object_service.go
modular/metadata/metadata_options.go
proto/modular/metadata/types/metadata.proto
store/bsdb/database.go
store/bsdb/filters.go
store/bsdb/group.go
store/bsdb/group_schema.go

implement new group api, list groups by name/prefix/sourceType and add default BsDBSwitchCheckIntervalSec
N/A
```
curl --location --request GET 'localhost:9133/?group&source-type=SOURCE_TYPE_ORIGIN&limit=10000&offset=0&name=e&prefix=t' \
--header 'Authorization: authTypeV2 ECDSA-secp256k1, Signature=1234567812345678123456781234567812345678123456781234567812345678'
```
* implement new group api, list groups by name/prefix/sourceType
* add default BsDBSwitchCheckIntervalSec

feat: get group lists

---

go.sum
modular/manager/manager_options.go

This pr will change the default interval for discontinue buckets.
Speedup
NA
* NA

feat: update the default interval for discontinue buckets

---

modular/approver/approve_task.go

Return the repeated approval, but not refuse.
N/A
N/A
N/A

feat: return repeated approval task

---

service/gateway/object_handler.go
store/bsdb/object.go

fix universal endpoint header and get object meta logic 
N/A
N/A
* downloader service (universal endpoint part)

fix: universal endpoint header and get object meta logic 

---

store/bsdb/filters.go

fix listobject filter error
N/A
N/A
* fix listobject filter error

fix: objects filter

---

base/gfspapp/upload_server.go
base/gfspclient/uploader.go
base/gnfd/gnfd.go
base/gnfd/gnfd_service.go
modular/uploader/upload_task.go
pkg/metrics/metric_items.go

Change get block height by ws protocol, it is more lightweight.
N/A
N/A
N/A

feat: change get block height by ws protocol

---

pkg/metrics/metric_items.go

Register perf metrics
N/A
N/A
N/A

fix: register perf metrics

---

modular/p2p/p2pnode/node.go

Add p2p bootstrap parser in eventloop
N/A
N/A
N/A

feat: add p2p bootstrap parser in eventloop

---

base/gfspapp/manage_server.go
base/gfspapp/task_options.go
base/gfspclient/manager.go
base/gfsptqueue/queue.go
base/gfsptqueue/queue_limit.go
modular/approver/approve_task.go
modular/downloader/download_task.go
modular/manager/manage_task.go
modular/manager/manager.go
modular/p2p/p2p_task.go
modular/receiver/receive_task.go
modular/uploader/upload_task.go
pkg/metrics/metric_items.go

1. Fix task queue bug
2. Add report done upload task mertics for stability test
3. Compatible the error that object already sealed from chain
N/A
N/A
N/A

feat: add protection for task queue

---

base/gfspapp/manage_server.go
base/gfsptqueue/queue.go
base/gfsptqueue/queue_limit.go
modular/manager/manage_task.go
pkg/metrics/metric_items.go

Fix task queue index error
N/A
N/A
N/A

fix: task queue index error

---

modular/metadata/metadata_object_service.go
store/bsdb/const.go
store/bsdb/database_mock.go
store/bsdb/filters.go
store/bsdb/group.go

* fix list group & list objects bugs
* update database_mock.go 
N/A
N/A
* fix listobjects slice bounds out of range [:-1] error
* refactor the group SQL to align with the new logic of the group table
* update database_mock.go

fix: list groups api

---

README.md

Update readme SP config.
N/A
N/A
N/A

docs: update readme sp config

---

CHANGELOG.md

Add changelog for  v0.2.2.alpha.1
N/A
N/A
N/A

docs: add changelog for v0.2.2.alpha.1

---

modular/blocksyncer/blocksyncer_indexer.go
modular/blocksyncer/blocksyncer_options.go

fix:blocksyncer block

---

base/gnfd/gnfd_service.go
modular/approver/approve_task.go
modular/executor/execute_task.go
modular/gater/admin_handler.go
pkg/metrics/metric_items.go

Add more metrics to perf get approval.
N/A.
N/A.
* Add the greenfield chain metrics and get approval workflow metrics.

perf: add more metrics to perf get approval

---

modular/blocksyncer/blocksyncer_indexer.go

fix:blocksyncer queue block

---

modular/blocksyncer/blocksyncer_indexer.go

fix:blocksyncer queue size

---

modular/blocksyncer/blocksyncer_indexer.go
modular/blocksyncer/blocksyncer_options.go

fix:delete blocksyncer processed queue

---

base/gfsptqueue/queue.go
base/gfsptqueue/queue_limit.go
base/types/gfsptask/task_key.go
modular/approver/approve_task.go
modular/approver/approver.go
modular/approver/approver_options.go
modular/gater/object_handler.go

Refactor task queue that opt index rest
N/A
N/A
N/A

refactor: task queue

---

modular/signer/signer_client.go

Fix signer error handle bug.
N/A
N/A
N/A

fix: signer panic

---

store/piecestore/storage/const.go
store/piecestore/storage/ldfs.go
store/piecestore/storage/object_storage.go

Piece store adds ldfs object storage
Note!!!
Not tested yet, just a draft
Support a new object storage minio
* ...

feat: add ldfs piecestore

---

modular/blocksyncer/blocksyncer_options.go

feat:blocksyncer add sleep

---

modular/executor/execute_task.go

Fix collect metrics bug
N/A
N/A
N/A

fix: seal metrics error

---

modular/executor/execute_task.go

Fix the bug that collects the seal metrics
N/A
N/A
N/A

fix: metrics collect bug

---

modular/blocksyncer/blocksyncer_indexer.go

test: add time elapse log

---

modular/executor/execute_replicate.go
modular/executor/executor.go

Add replicate metrics
N/A
N/A
N/A

feat: add replicate metrics

---

modular/blocksyncer/blocksyncer_indexer.go

fix: add logs for time elpased

---

modular/executor/execute_replicate.go
modular/executor/executor.go

Add replicate metrics
N/A
N/A
N/A

feat: add replicate metrics (#599)

---

base/gnfd/gnfd_service.go
core/module/modular.go
core/module/null_modular.go
modular/executor/execute_replicate.go
modular/executor/executor.go
modular/executor/executor_options.go
modular/manager/manager.go

Opt executor goroutine model
N/A
N/A
N/A

feat: opt executor goroutine model

---

Makefile
base/gfspapp/app.go
base/gfspapp/app_options.go
base/gfspapp/grpc_server.go
base/gfspapp/manage_server.go
base/gfspconfig/config.go
cmd/command/query.go
cmd/utils/init_env.go
deployment/localup/env.info
deployment/localup/localup.sh
modular/authorizer/authorizer.go
modular/executor/execute_replicate.go
modular/executor/execute_task.go
modular/gater/admin_handler.go
modular/gater/auth_handler.go
modular/gater/gater_options.go
modular/gater/object_handler.go
modular/manager/manager.go
modular/p2p/p2pnode/approval.go
modular/p2p/p2pnode/node.go
modular/p2p/p2pnode/ping.go

Fix variable names for standards
N/A
N/A
N/A

fix: fix variable names for standards

---

base/gfspclient/downloader.go
modular/gater/object_handler.go

feat: add metric download
* ...

feat: add metric download

---

base/gfspclient/downloader.go
modular/gater/object_handler.go

feat: add perf metrics

---

base/gfspapp/task_options.go
base/gfsptqueue/queue.go
base/gfsptqueue/queue_limit.go
base/gnfd/gnfd.go
base/gnfd/gnfd_service.go
base/types/gfsptask/task.go
core/consensus/consensus.go
modular/downloader/download_task.go
modular/executor/executor.go
modular/executor/executor_options.go
modular/manager/manage_task.go
modular/manager/manager.go
modular/manager/manager_options.go
modular/signer/signer.go
modular/signer/signer_client.go

Add reject unseal object retry and confirm
N/A
N/A
N/A

feat: add reject unseal object retry and confirm

---

modular/executor/execute_task.go
modular/manager/manage_task.go
modular/uploader/upload_task.go
pkg/metrics/metric_items.go

Add metrics for upload
N/A
N/A
N/A

feat: add metrics for upload

---

modular/blocksyncer/blocksyncer_indexer.go
modular/blocksyncer/blocksyncer_options.go

fix:blocksyncer queue

---

base/gfspapp/task_options.go
modular/executor/execute_task.go
modular/executor/executor.go
modular/manager/manage_task.go
modular/signer/signer_client.go

Delete reject unseal object logic
N/A
N/A
N/A

chore: delete reject unseal object logic

---

modular/signer/signer_client.go

Fix signer nonce mismatch under fullnode.
N/A
N/A
N/A

fix: signer nonce mismatch under fullnode

---

base/gfspconfig/config.go
modular/signer/signer_client.go
modular/signer/signer_options.go

fix sequence mismatch issue when batch txs within same block
Na
Na
* Na

fix: broadcast tx bypass simulation and sync mode

---

base/gfspconfig/config.go
modular/signer/signer_client.go
modular/signer/signer_options.go

use sync mode and no simulation
NA
NA
* ...

fix: broadcast txmode

---

base/gfspapp/manage_server.go
base/gfspapp/task_options.go
base/gfspapp/upload_server.go
base/gfspclient/manager.go
core/spdb/spdb.go
modular/executor/execute_replicate.go
modular/executor/execute_task.go
modular/executor/executor.go
modular/gater/object_handler.go
store/sqldb/const.go
store/sqldb/store.go
store/sqldb/upload_event.go
store/sqldb/upload_event_schema.go

Add report task type check
N/A
N/A
N/A

fix: report task type check

---

base/gfspapp/task_options.go
base/gfsptqueue/queue.go
base/gfsptqueue/queue_limit.go
modular/manager/manager.go

Change default task timeout
N/A
N/A
N/A

chore: change task timeout

---

CHANGELOG.md
go.mod
go.sum
test/e2e/spworkflow/e2e_test.sh

This PR is used for releasing v0.2.2.
N/A
N/A
* CHANGELOG

feat: release v0.2.2

---

base/types/gfsptask/approval.go
base/types/gfsptask/task_key.go

change approval key
N/A
N/A
N/A

feat: change approval key

---

modular/approver/approve_task.go

ignore push approval to queue error
N/A
N/A
N/A

chore: ignore push approval to queue error

---

base/types/gfsptask/approval.go
base/types/gfsptask/task_key.go

Fix approval task key
N/A
N/A
N/A

fix: approval task key

---

base/types/gfsptask/approval.go
base/types/gfsptask/task_key.go
modular/downloader/download_task.go
modular/downloader/downloader.go
modular/downloader/downloader_options.go

Add piece data cache in downloader
N/A
N/A
N/A

feat: add download cache

---

base/gfspconfig/config.go
modular/signer/signer_client.go
modular/signer/signer_options.go

correct gas limit and handle sequence mismatch problem(status code 32)
correct gas limit and handle sequence mismatch problem(status code 32)
* ...

fix: correct gas limit and handle code:32 error

---

modular/downloader/download_task.go
modular/executor/execute_task.go
modular/gater/admin_handler.go
modular/gater/const.go
modular/gater/object_handler.go

1) fix download recovery condition
2) fix recovery quota
fix recovery error 
NA
*fix recovery error

fix: fix data recovery

---

cmd/storage_provider/main.go

fix: comment medatadata for later adaption

fix: comment medatadata for later adaption

---

base/gfspapp/app.go
base/gfspapp/manage_server.go
modular/manager/manage_task.go
modular/manager/manager.go

Fix bug that concurrent read and write task in queue.
N/A
N/A
N/A

fix: write task in queue

---

base/gfspclient/metadata.go
modular/metadata/metadata_sp_exit_service.go
proto/buf.lock
proto/modular/metadata/types/metadata.proto

update buf version
N/A
N/A
*  update buf version

feat: update buf version

---

modular/gater/router.go
modular/gater/router_test.go

fix  the off chain auth api routers and add related UT
* put off chain auth api routers in advance
* add related UT

fix: re-enable the off chain auth api and add related ut

---

.github/workflows/docker-ci.yml

feat: add docker-ci action for dev
* ...

feat: add docker-ci action for dev

---

modular/executor/execute_replicate.go
modular/manager/manage_task.go

chore: append executor log to manager

---

modular/executor/executor.go
modular/executor/executor_options.go
modular/gater/object_handler.go

chore: add metrics

---

store/piecestore/storage/aliyunfs.go
store/piecestore/storage/const.go
store/piecestore/storage/object_storage.go

feat: implement aliyun oss storage

---

modular/authenticator/authenticator.go

The logic of checking the existence of the account has been removed from the VerifyAuthentication function which is used to verify authorization of the request to SP.  The reasons for the removal are as follows:：
1）Data marketplace users only operate on BSC and have no transactions on Greenfield.
2）During batch upload, a temporary account is generated, and the gas and fees for this temporary account are deducted from the user's account (with authorization). This temporary account has not yet been created on the chain, but actions like createObject are performed
support marketplace user case
NA
*  remove checking the existence of the account

fix: fix authorization

---

.github/workflows/docker-ci.yml

fix: update docker-ci.yml

---

base/gfspclient/gater.go
base/gfspvgmgr/virtual_group_manager.go
modular/blocksyncer/modules/registrar.go
modular/executor/executor.go
modular/executor/migrate_task.go
modular/gater/admin_handler.go
modular/metadata/metadata_sp_exit_service.go

Fix migrate piece computing integrity hash.
N/A
N/A
* N/A

fix: fix migrate piece computing integrity hash

---

base/gfspapp/grpc_server.go
base/gfspclient/client.go
base/gfspclient/downloader.go

feat: using keepalive age to reduce load imbalance when scaling
* ...

feat: using keepalive age to reduce load imbalance when scaling

---

go.mod
go.sum
modular/signer/signer.go

feat: adapt bls change

---

base/gfspapp/app.go
base/gfspapp/manage_server.go
base/gfspapp/task_options.go
modular/executor/execute_task.go
modular/executor/executor.go
modular/executor/executor_options.go
modular/manager/manage_task.go
modular/manager/manager.go
modular/manager/manager_options.go
modular/uploader/upload_task.go

* Delete dispatch task global mutex
* Fix executor err == nil bug
N/A
N/A
N/A

refactor: manager dispatch task

---

base/gfspapp/task_options.go
base/gfspclient/client.go
base/gfspclient/metadata.go
base/gfspclient/uploader.go
base/gnfd/gnfd_service.go
modular/executor/execute_task.go
modular/gater/admin_handler.go
modular/gater/bucket_handler.go
modular/gater/object_handler.go
modular/gater/request_context.go
modular/manager/manage_task.go
store/sqldb/upload_event.go

* Refactor query object from metadata, not query chain.
* Replace NeedVerifyAuthentication func by SkipVerifyAuthentication func, for signV2.
N/A
N/A
N/A

refactor: receive task query object info from metadata

---

cmd/command/recovery.go
modular/downloader/download_task.go
modular/downloader/downloader_options.go

add err code checking when challenging recovery
fix error
NA
* add err code checking when challenging recovery

fix: fix challenge data recovery

---

cmd/command/recovery.go
modular/downloader/download_task.go
modular/downloader/downloader_options.go

add err code checking when challenging recovery
fix error
NA
* add err code checking when challenging recovery

fix: fix challenge data recovery 

---

modular/authenticator/authenticator.go
modular/gater/object_handler.go
modular/metadata/metadata_permission_service.go

feat: verify object permission by meta service
* ...

feat: verify object permission by meta service

---

base/gfspapp/sign_server.go
base/gfspclient/signer.go
core/module/modular.go
core/module/null_modular.go
modular/metadata/metadata_sp_exit_service.go
modular/signer/signer.go
modular/signer/signer_client.go
proto/base/types/gfspserver/sign.proto

Signer module implements complete migrate bucket interface.
N/A
N/A
* N/A

feat: signer module implements complete migrate bucket interface

---

modular/gater/object_handler.go

Change upload task create time from receive request
N/A
N/A
N/A

chore: change upload task create time from receive request

---

modular/blocksyncer/blocksyncer_indexer.go
modular/blocksyncer/blocksyncer_options.go

fix:add bs log

---

modular/blocksyncer/blocksyncer_indexer.go

feat:add bs log

---

modular/executor/migrate_task.go

fix: comment mockHandleMigratePiece function

---

.github/workflows/build-test.yml
.github/workflows/code-lint.yml
.github/workflows/commit-lint.yml
.github/workflows/e2e-test.yml
.github/workflows/gosec.yml
.github/workflows/proto-lint.yml
.github/workflows/unit-test.yml

chore: update action yml

---

modular/gater/router.go

fix: gateway register migration bucket approval handler

---

base/gfspapp/sign_server.go
base/gfspclient/signer.go
core/module/modular.go
core/module/null_modular.go
modular/signer/signer.go
modular/signer/signer_client.go
proto/base/types/gfspserver/sign.proto

feat: signer adds swap out interface

---

modular/gater/admin_handler.go
modular/gater/request_context.go

the receiver needs to check the signature of the primary SP and check the request account if it is really the primary on chain
fix receiver
NA
*  fix receiver handler

fix: add verify receive task signature and verify primary SP

---

base/gfspapp/sign_server.go
base/gfspclient/signer.go
core/module/modular.go
core/module/null_modular.go
modular/signer/signer.go
modular/signer/signer_client.go
proto/base/types/gfspserver/sign.proto

feat: signer adds complete swap out interface

---

base/gfspapp/sign_server.go
base/gfspclient/signer.go
core/module/modular.go
core/module/null_modular.go
modular/signer/signer.go
modular/signer/signer_client.go
proto/base/types/gfspserver/sign.proto

feat: signer adds complete sp exit interface

---

base/types/gfsptask/upload.go
core/task/task.go
modular/gater/object_handler.go
modular/manager/manage_task.go
proto/base/types/gfsptask/task.proto

sp exit adapts resumable-upload
NA
NA
* NA
* ...

feat: sp exit adapts resumable-upload

---

base/gfspapp/sign_server.go
base/gfspclient/signer.go
core/module/modular.go
core/module/null_modular.go
modular/gater/admin_handler.go
modular/receiver/receive_task.go
modular/signer/signer.go
proto/base/types/gfspserver/sign.proto

fix: rename sign secondary bls as sign secondary seal bls

---

base/gfspapp/sign_server.go
base/gfspclient/gater.go
base/gfspclient/signer.go
base/gfspconfig/config.go
core/module/modular.go
core/module/null_modular.go
modular/gater/const.go
modular/gater/migrate_handler.go
modular/gater/router.go
modular/signer/signer.go
modular/signer/signer_options.go
proto/base/types/gfspserver/sign.proto

feat: gateway adds get swap out approval handler

---

base/gfspapp/sign_server.go
base/gfspclient/signer.go
cmd/command/migrate.go
cmd/command/recovery.go
cmd/storage_provider/main.go
core/module/modular.go
core/module/null_modular.go
modular/signer/signer.go
modular/signer/signer_client.go
proto/base/types/gfspserver/sign.proto

feat: signer adds sp exit interface

---

base/gfspclient/gater.go
modular/gater/const.go
modular/gater/migrate_handler.go
modular/signer/signer.go

fix: optimize get swap out approval and bls approval

---

base/gfspapp/manage_server.go
base/gfspclient/uploader.go
base/gfsptqueue/queue.go
base/gfsptqueue/queue_limit.go
base/types/gfsptask/approval.go
base/types/gfsptask/download.go
base/types/gfsptask/gc.go
base/types/gfsptask/recovery.go
base/types/gfsptask/upload.go
modular/gater/object_handler.go
modular/manager/manage_task.go
modular/uploader/upload_task.go

revert task timestamp
N/A
N/A
N/A

chore: revert task time stamp

---

base/types/gfsptask/approval.go
base/types/gfsptask/download.go
base/types/gfsptask/gc.go
base/types/gfsptask/recovery.go
base/types/gfsptask/task.go
base/types/gfsptask/task_key.go
base/types/gfsptask/upload.go
cmd/command/debug.go
core/task/null_task.go
core/task/task.go
modular/gater/admin_handler.go
modular/gater/request_context.go
proto/base/types/gfsptask/task.proto

add user address to task
N/A
N/A
N/A

feat: add user address to task

---

base/gfspconfig/config.go
core/spdb/spdb.go
modular/manager/manager.go
modular/manager/manager_options.go
store/sqldb/upload_object.go

Add timeout limit for loading task from db.
N/A
N/A
N/A

feat: add timeout limit for loading task from db

---

modular/authenticator/authenticator.go
modular/gater/admin_handler.go
modular/gater/bucket_handler.go
modular/gater/object_handler.go
modular/gater/request_context.go

Fix skip auth v0.2.2
N/A
N/A
N/A

fix: skip auth v0.2.2

---

modular/authenticator/authenticator.go

fix: return chain auth error
N/A
N/A
N/A

fix: return chain auth error

---

modular/gater/const.go
modular/gater/metadata_handler.go

add include removed query param for list object and list buckets
N/A
N/A
* add include removed query param for list object and list buckets
* remove Authorization header

fix: add include removed query param

---

base/gfspvgmgr/virtual_group_manager.go
core/module/modular.go
core/module/null_modular.go
modular/executor/migrate_task.go
modular/manager/bucket_migrate_scheduler.go
modular/manager/sp_exit_scheduler.go

fix: use src sp id to query index

---

go.mod
go.sum
modular/blocksyncer/blocksyncer_indexer.go

fix:blocksyncer version

---

modular/approver/approver.go

Chore compatibility get height failed in get approval.
N/A
N/A
N/A

chore: compatibility get height failed in get approval

---

go.mod
go.sum
modular/blocksyncer/blocksyncer_indexer.go

fix:juno version

---

go.mod
go.sum

Fixed a bug where blocksyncer could not update bucket visibility

fix:bucket visibility

---

base/gfspclient/manager.go
modular/downloader/download_task.go
modular/executor/executor.go
modular/receiver/receive_task.go

Refactor report task to manager by async.
N/A
N/A
N/A

refactor: async report task

---

base/gfspclient/manager.go
modular/downloader/download_task.go
modular/executor/executor.go
modular/receiver/receive_task.go

Refactor report task to manager by async.
N/A
N/A
N/A

refactor: async report task v0.2.3

---

modular/manager/manager.go
modular/manager/migrate_service.go

adapt sp id ListExpiredBucketsBySp
N/A
N/A
*adapt sp id ListExpiredBucketsBySp

fix: adapt sp id ListExpiredBucketsBySp

---

go.mod
go.sum
store/piecestore/storage/aliyunfs.go

To support accessing AliCloud OSS with K8S ServiceAccount & AWS SDK, need to fetch credentials with AliCloud SDK and then construct a AWS static credential provider to work.
To be able to access AliCloud OSS with K8S ServiceAccount authentication & AWS SDK

fix: fix aliyunfs by fetching credentials with AliCloud SDK

---

cmd/command/query.go
go.mod
modular/executor/execute_task.go
modular/executor/executor.go
modular/executor/migrate_task.go
modular/uploader/upload_task.go

fix: refactor get segment integrity cli

---

go.mod
go.sum
modular/blocksyncer/blocksyncer_indexer.go
modular/blocksyncer/blocksyncer_options.go
modular/blocksyncer/database/object.go
modular/blocksyncer/modules/events/sp_events_handler.go
modular/blocksyncer/modules/object/object_handler.go
modular/blocksyncer/modules/prefixtree/prefix_tree.go

feat:blocksyncer performance

---

base/gfspapp/manage_server.go
base/gfspclient/manager.go
deployment/localup/localup.sh
modular/gater/migrate_handler.go
modular/gater/object_handler.go
modular/manager/migrate_service.go
modular/manager/sp_exit_scheduler.go

chore: polish some code

---

modular/blocksyncer/blocksyncer_options.go

fix:blocksyncer panic

---

base/gfspvgmgr/virtual_group_manager.go
base/gnfd/gnfd_service.go
cmd/storage_provider/main.go
modular/executor/migrate_task.go
modular/manager/manage_task.go
modular/manager/manager.go
modular/manager/manager_options.go

chore: refine some code

---

.github/workflows/sp-exit-e2e-test.yml
base/types/gfsptask/migrate_gvg.go
cmd/command/exit_migrate.go
modular/executor/migrate_task.go
modular/gater/errors.go
modular/gater/migrate_handler.go
modular/gater/object_handler.go
modular/manager/bucket_migrate_scheduler.go
modular/manager/manager_options.go
modular/manager/sp_exit_scheduler.go
test/e2e/spworkflow/e2e_test.sh

test: add sp exit e2e test

---

modular/executor/migrate_task.go
test/e2e/spworkflow/e2e_test.sh

fix: fix migrate error piece

---

.github/workflows/e2e-sdk.yml
test/e2e/spworkflow/e2e_test.sh

add SP E2E Test with Go-SDK
Currently, only one test, e2e_migrate_bucket_test.go, has been added. Additional tests can be added later if needed.
NA
* NA
* ...

feat: add a new github workflow for bucket migrate

---

modular/executor/migrate_task.go

fix: fix check bucket migration bucket id

---

modular/uploader/upload_task.go

Print upload err log for debug.
N/A.
N/A.
N/A.

fix: print upload err log

---

store/piecestore/storage/aliyunfs.go

fix: aliyunfs update security token every 30 minutes

---

cmd/command/recovery.go
modular/downloader/download_task.go
modular/downloader/downloader.go

fix recover command caused by using exist fuction errr
fix bug
* ...

fix: fix recover command

---

modular/executor/migrate_task.go
util/virtual_group.go

fix: optimize object migration logic

---

modular/blocksyncer/blocksyncer_indexer.go
modular/gater/metadata_handler.go
pkg/metrics/metric_items.go
store/bsdb/block.go
store/bsdb/bucket.go
store/bsdb/common.go
store/bsdb/const.go
store/bsdb/event_migration_bucket.go
store/bsdb/event_sp_exit.go
store/bsdb/event_swap_out.go
store/bsdb/global_virtual_group.go
store/bsdb/global_virtual_group_family.go
store/bsdb/group.go
store/bsdb/local_virtual_group.go
store/bsdb/object.go
store/bsdb/payment.go
store/bsdb/permission.go
store/bsdb/prefix.go

Adding metadata and block syncer monitors
N/A
N/A
* block syncer

feat: metadata and block syncer monitor

---

base/gfspconfig/config.go
base/gfspvgmgr/virtual_group_manager.go
core/vgmgr/virtual_group_manager.go
deployment/localup/localup.sh
modular/manager/manage_task.go
modular/manager/manager.go
modular/manager/manager_options.go

Add generate gvg sp policy.
N/A.
N/A.
* N/A.

feat: add generate gvg sp policy

---

store/piecestore/storage/aliyunfs.go

Wrap a credential provider for aliyunfs to fix the credential expiration issue.
Fix the credential expiration issue.
NA
* Add a credential provider for aliyun

fix: fix aliyun credential expiration issue

---

modular/blocksyncer/blocksyncer_indexer.go
modular/blocksyncer/modules/objectidmap/object_id_map.go

fix:blocksyncer object map id

---

base/gfspapp/grpc_server.go
base/gfspclient/client.go
base/gfspclient/downloader.go

feat: revert grpc keepalive params
* ...

feat: revert grpc keepalive params

---

pkg/metrics/metric_items.go

fix:blocksyncer monitor

---

base/gfspclient/metadata.go
go.mod
go.sum
modular/gater/const.go
modular/gater/metadata_handler.go
modular/gater/router.go
modular/gater/router_test.go
modular/metadata/metadata_bucket_service.go
modular/metadata/metadata_sp_service.go
proto/modular/metadata/types/metadata.proto
store/bsdb/const.go
store/bsdb/database.go
store/bsdb/storage_provider.go
store/bsdb/storage_provider_schema.go

In order to replace chain api
spInfo, err := a.baseApp.Consensus().QuerySP(context.Background(), a.baseApp.OperatorAddress())
N/A
N/A
* support query sp api

feat: support query sp

---

modular/manager/sp_exit_scheduler.go
modular/signer/signer_client.go
util/virtual_group.go

Refine swap out tx error.
Add retry logic after swap out tx failure.
N/A.
* Signer.

fix: polish sp exit tx failed workflow v0.2.3

---

modular/manager/sp_exit_scheduler.go
modular/signer/signer_client.go
util/virtual_group.go

Refine swap out tx error.
Add retry logic after swap out tx failure.
N/A.
* Signer.

fix: polish sp exit tx failed workflow

---

modular/manager/bucket_migrate_scheduler.go

cherry-pick from #907 
NA
NA
* NA
* ...

feat: replace SecondarySp which is in STATUS_GRACEFUL_EXITING

---

modular/executor/migrate_task.go
modular/gater/migrate_handler.go
modular/manager/bucket_migrate_scheduler.go
modular/manager/sp_exit_scheduler.go

Fix when selecting the target sp, you can choose primary sp as the target gvg's secondary sp node.
NA
NA
* NA
* ...

fix: pick sp can select primary sp

---

store/piecestore/piece/piece_store.go
test/e2e/piecestore/b2_test.go
test/e2e/piecestore/disk_file_test.go
test/e2e/piecestore/helper_test.go
test/e2e/piecestore/memory_test.go
test/e2e/piecestore/minio_test.go
test/e2e/piecestore/s3_test.go
test/e2e/piecestore/sharding_test.go

Reverts bnb-chain/greenfield-storage-provider#916

Revert "fix: failed to new piece store will panic"

---

base/gfspclient/gater.go
modular/downloader/download_task.go
modular/executor/migrate_task.go
modular/manager/sp_exit_scheduler.go

fix: refine sp exit scheduler v0.2.3

---

base/gfspclient/gater.go
modular/downloader/download_task.go
modular/executor/migrate_task.go
modular/manager/sp_exit_scheduler.go

fix: refine sp exit scheduler

---

modular/uploader/upload_task.go

fix: insert integrity hash to db

---

modular/uploader/upload_task.go

fix: insert integrity hash to db v0.2.3

---

modular/executor/migrate_task.go
modular/manager/manager.go
modular/manager/sp_exit_scheduler.go

fix: migrate from last migrated object id v0.2.3

---

modular/executor/migrate_task.go
modular/manager/manager.go
modular/manager/sp_exit_scheduler.go

fix: migrate from last migrated object id

---

modular/gater/object_handler.go

Check SP and bucket status when putting object.
N/A
N/A
* N/A

fix: check sp and bucket status when putting object

---

modular/gater/errors.go

Fix repeated error msg(xml format) to return the client.
N/A
N/A
N/A

fix: repeated error xml msg

---

modular/blocksyncer/blocksyncer_indexer.go
modular/blocksyncer/blocksyncer_options.go
pkg/metrics/metric_items.go

feat:time Ticker

---

store/piecestore/storage/aliyunfs.go
store/piecestore/storage/aliyunfs_test.go
store/piecestore/storage/b2.go
store/piecestore/storage/checksum_test.go
store/piecestore/storage/disk_file_test.go
store/piecestore/storage/ldfs.go
store/piecestore/storage/ldfs_test.go
store/piecestore/storage/memory.go
store/piecestore/storage/memory_test.go
store/piecestore/storage/minio.go
store/piecestore/storage/minio_test.go
store/piecestore/storage/object_storage_test.go
store/piecestore/storage/s3.go
store/piecestore/storage/s3_test.go
store/piecestore/storage/sharding_test.go

test: piece store pkg storage dir adds unit test

---

modular/gater/auth_handler.go

We are going to convert all json response of APIs to xml reponses.
This PR is for Auth part.
The following API will have xml response instead of json response
* requestNonce API
* updateUserPublicKey API

feat: change auth api response from json to xml

---

modular/blocksyncer/blocksyncer.go
modular/blocksyncer/blocksyncer_indexer.go
modular/blocksyncer/blocksyncer_options.go

The real-time block tracing mode is added to reduce memory usage

feat:blocksyncer add realtime mode

---

modular/blocksyncer/blocksyncer.go
modular/blocksyncer/blocksyncer_indexer.go
modular/blocksyncer/blocksyncer_options.go

The real-time block tracing mode is added to reduce memory usage

feat:blocksyncer add real time mode

---

modular/blocksyncer/database/group.go
modular/blocksyncer/modules/group/group_handler.go

fix:blocksyncer delete group bug

---

CHANGELOG.md

Draft release for v0.2.4-alpha.9.
FEATURES
* [#989](https://github.com/bnb-chain/greenfield-storage-provider/pull/989) feat: impl group apis and fix verify permission bug
* [#1008](https://github.com/bnb-chain/greenfield-storage-provider/pull/1008) feat: change auth api response from json to xml
* [#1010](https://github.com/bnb-chain/greenfield-storage-provider/pull/1010) feat:blocksyncer add realtime mode
* [#1015](https://github.com/bnb-chain/greenfield-storage-provider/pull/1015) feat: retrieve groups where the user is the owner
* [#1012](https://github.com/bnb-chain/greenfield-storage-provider/pull/1012) feat: error handle updates to provide useful messages
* [#1025](https://github.com/bnb-chain/greenfield-storage-provider/pull/1025) feat: change json response body to xml
BUGFIX
* …

release: draft release for v0.2.4-alpha.9

---

modular/signer/signer_client.go

modify signer BroadcastMode to sync mode
* ...

fix: modify signer BroadcastMode to sync mode

---

modular/blocksyncer/blocksyncer_options.go
modular/metadata/metadata_options.go
pkg/metrics/metric_items.go

Add go routine metrics for metadata and block syncer
N/A
N/A
* metrics

feat: add go routine metrics

---

modular/metadata/metadata_object_service.go

fix nil pointer err caused by ObjectDetails
N/A
N/A
* fix nil pointer err caused by ObjectDetails

fix: nil pointer err caused by ObjectDetails

---

base/gfspapp/app.go
base/gfspapp/app_options.go
base/gfspapp/app_test.go
modular/metadata/metadata_options.go

remove backup bsdb
N/A
N/A
* remove backup bsdb

fix: remove backup db

---

base/gfspapp/app.go
base/gfspapp/app_options.go
base/gfspapp/app_test.go
base/gfspconfig/config.go
deployment/localup/localup.sh
modular/blocksyncer/blocksyncer_options.go
modular/metadata/metadata_options.go
modular/metadata/metadata_sp_service.go
store/bsdb/store.go

Simplify block syncer and metadata configuration
Delete the Backup DB

feat:delete  redundant configurations

---

base/gfspapp/app.go
base/gfspapp/app_options.go
base/gfspapp/app_test.go
base/gfspconfig/config.go
deployment/localup/localup.sh
modular/blocksyncer/blocksyncer_options.go
modular/metadata/metadata_options.go
modular/metadata/metadata_sp_service.go
store/bsdb/store.go

Simplify block syncer and metadata configuration
Delete the Backup DB

feat:delete bs cfg

---

.testcoverage.yml
base/gfspapp/app.go
base/gfspapp/app_test.go
base/gfspapp/approval_server_test.go
base/gfspapp/authenticator_server.go
base/gfspapp/authenticator_server_test.go
base/gfspapp/download_server.go
base/gfspapp/download_server_test.go
base/gfspapp/helper_test.go
base/gfspapp/manage_server_test.go
base/gfspapp/p2p_server_test.go
base/gfspapp/query_server_test.go
base/gfspapp/rcmgr_server_test.go
base/gfspapp/receive_server_test.go
base/gfspapp/sign_server.go
base/gfspapp/signer_server_test.go
base/gfspapp/upload_server_test.go
base/gnfd/gnfd_service.go
modular/approver/approve_task.go
modular/approver/approve_task_test.go

test: gfspapp pkg adds UTs part II

---

base/gfspconfig/config_test.go
base/gfspconfig/customize_config.go
base/gfspconfig/customize_config_test.go
base/gfsppieceop/piece_op.go
base/gfsppieceop/piece_op_test.go
base/gfsprcmgr/error_test.go

gfspconfig and gfsppieceop pkg add UTs.
N/A
* N/A

test: gfspconfig and gfsppieceop pkg add UTs

---

base/gfspapp/app_options.go
base/gfsprcmgr/scope.go

Add more resource manager log.
N/A.
N/A.
* resource manager.

fix: add more resource manager log v0.2.4

---

base/types/gfsperrors/error_test.go
base/types/gfsplimit/limit.go
base/types/gfsplimit/limit_test.go
base/types/gfspp2p/p2p_test.go
base/types/gfsptask/approval.go
base/types/gfsptask/approval_test.go
base/types/gfsptask/download_test.go
base/types/gfsptask/gc_test.go
base/types/gfsptask/migrate_gvg.go
base/types/gfsptask/migrate_gvg_test.go
base/types/gfsptask/recovery_test.go
base/types/gfsptask/task.go
base/types/gfsptask/task_key_test.go
base/types/gfsptask/task_test.go
base/types/gfsptask/upload_test.go

base/types directory adds UTs.
N/A
* N/A

test: base/types directory adds UTs

---

modular/blocksyncer/modules/group/group_handler.go

fix blocksyncer group bug
nothing
nothing
* nothing

fix:bs panic

---

modular/metadata/metadata_permission_service.go

[add a description of your changes here...](fix: verify permission if expiration time = 0 bug)
N/A
N/A
* fix verify permission if expiration time = 0

 fix: verify permission if expiration time = 0 bug

---

.testcoverage.yml
base/gfspclient/approver_test.go
base/gfspclient/authenticator.go
base/gfspclient/authenticator_test.go
base/gfspclient/client.go
base/gfspclient/client_test.go
base/gfspclient/downloader_test.go
base/gfspclient/gater.go
base/gfspclient/gater_test.go
base/gfspclient/helper_test.go
base/gfspclient/interface.go
base/gfspclient/interface_mock.go
base/gfspclient/manager.go
base/gfspclient/manager_test.go
base/gfspclient/metadata.go
base/gfspclient/p2p_test.go
base/gfspclient/query_task.go
base/gfspclient/query_task_test.go
base/gfspclient/receiver_test.go
base/gfspclient/signer_test.go
base/gfspclient/uploader.go
base/gfspclient/uploader_test.go
base/gfsprcmgr/resource.go
modular/gater/auth_handler_test.go
util/rpc/jsonrpc/client/http_json_client_test.go
util/utils_test.go

base/gfspclient pkg adds UTs.
N/A
* N/A

test: base/gfspclient pkg adds UTs

---

modular/manager/manage_task.go

this pr fix self SP id retrieval. 
* ...

fix: fix get self sp ID

---

base/gfspclient/interface.go
base/gfspclient/interface_mock.go
base/gfspclient/metadata.go
modular/gater/auth_handler.go
modular/gater/metadata_handler.go
store/piecestore/storage/checksum.go
store/piecestore/storage/checksum_test.go

fix: sec issue about conversion alerts
https://github.com/bnb-chain/greenfield-storage-provider/security/code-scanning/8
https://github.com/bnb-chain/greenfield-storage-provider/security/code-scanning/7
https://github.com/bnb-chain/greenfield-storage-provider/security/code-scanning/2

fix: sec issue about conversion alerts

---

modular/manager/manage_task.go

this pr fix self SP id retrieval.
* ...

fix: self sp id retrieval

---

modular/downloader/download_task_test.go
modular/uploader/upload_task.go
modular/uploader/uploader.go
modular/uploader/uploader_options.go
modular/uploader/uploader_options_test.go
modular/uploader/uploader_task_test.go
modular/uploader/uploader_test.go

modular/uploader pkg adds UTs.
N/A
* N/A

test: modular/uploader pkg adds UTs

---

store/sqldb/off_chain_auth_key.go
store/sqldb/off_chain_auth_key_test.go

GetNonce API is cheap for attackers to generate massive requests of random addresses (and domains). It is
not recommended to persist the information, as it could lead to database flooding.
* Just respond to the default value for GetNonce requests.
* Insert the initial value when first updating user key

feat: only persist the init off-chain-auth record when first updating rather than first querying

---

.testcoverage.yml
base/gfspclient/uploader.go
modular/gater/admin_handler.go
modular/gater/admin_handler_test.go
modular/gater/bucket_handler.go
modular/gater/bucket_handler_test.go
modular/gater/errors.go
modular/gater/migrate_handler.go
modular/gater/migrate_handler_test.go
modular/gater/object_handler.go
modular/gater/object_handler_test.go
modular/gater/request_context.go
modular/gater/request_context_test.go
modular/gater/router.go

modular/gater pkg adds UTs part II.
N/A
* N/A

test: modular/gater pkg adds UTs part II

---

modular/metadata/metadata_permission_service.go

fix include private cause bucket not found bug
N/A
N/A
* fix include private cause bucket not found bug

fix: include private cause bucket not found

---

modular/blocksyncer/modules/group/module.go

fix:bs groups unique index
we need fix group data about unique key
nothing
* mysql table `groups` have some changes

fix:bs groups unique index

---

base/types/gfsptask/recovery.go
base/types/gfsptask/upload.go
modular/gater/admin_handler.go
modular/gater/admin_handler_test.go
modular/gater/errors.go
modular/gater/object_handler.go

check the expire time of SP recovery and receiver task
* ...

feat: support expire time check of SP task info

---

base/gfspclient/interface.go
base/gfspclient/interface_mock.go
modular/approver/approver_test.go
modular/executor/execute_replicate.go
modular/executor/execute_replicate_test.go
modular/executor/execute_task.go
modular/executor/executor.go
modular/executor/executor_options.go
modular/executor/executor_options_test.go
modular/executor/executor_task_test.go
modular/executor/executor_test.go
modular/executor/migrate_task.go

modular/executor pkg adds UTs.
N/A
* N/A

test: modular/executor pkg adds UTs

---

store/bsdb/permission.go

fix expiration time for list object policies
N/A
N/A
* fix expiration time for list object policies

fix: expiration time for list object policies

---

store/bsdb/permission.go

fix: effect allow issue for list object policies
N/A
N/A
* fix: effect allow issue for list object policies

fix: effect allow issue for list object policies

---

modular/executor/execute_task.go
modular/executor/migrate_task.go
modular/gater/admin_handler.go
modular/gater/errors.go
modular/gater/migrate_handler.go
modular/gater/object_handler.go

1. add permission check to replicate the data on secondary sp
2. add the err catch of HTTP write error of recovery or migration
fix permission
NA
* ...

fix:  add replicate check permission

---

base/gfspapp/upload_server.go

Fix uploader server read closed channel.
In some extreme cases, uploader server may read data from closed channel.
N/A
* N/A

fix: fix uploader server read closed channel

---

modular/gater/errors.go
modular/gater/object_handler.go
modular/manager/bucket_migrate_scheduler.go
modular/manager/manage_task.go
modular/metadata/metadata_bucket_service.go
modular/metadata/metadata_query_service.go
store/sqldb/upload_object.go

1. Fix manager duplicate entry when inserting upload progress.
2. Fix query upload progress when record not found returns HTTP 404 not 500.
Optimize code logics.
N/A
* N/A

fix: fix manager duplicate entry when inserting upload progress

---

modular/blocksyncer/modules/group/module.go

delete fix group data job code
Clean up dead code
nothing
* delete fix group data job code

fix:delete group fix job

---

CHANGELOG.md
go.mod
go.sum
test/e2e/spworkflow/e2e_test.sh

release: draft release for v0.2.6-hf.1
N/A
N/A
* N/A

docs: release: draft release for v0.2.6-hf.1

---

base/types/gfsptask/upload.go
go.mod

fix a var initialization. 
* ...

fix: fix the init idx

---

CHANGELOG.md

release: draft release for v0.2.6-hf.2
N/A
N/A
* N/A

docs: release: draft release for v0.2.6-hf.2

---

CHANGELOG.md

Draft release for v1.0.1
FEATURES
* [#1181](https://github.com/bnb-chain/greenfield-storage-provider/pull/1181) feat: api rate limiter refactor
* [#1188](https://github.com/bnb-chain/greenfield-storage-provider/pull/1188) feat:blocksyncer fix data command
BIGFIX
* [#1186](https://github.com/bnb-chain/greenfield-storage-provider/pull/1186) fix:batch delete group member
* [#1187](https://github.com/bnb-chain/greenfield-storage-provider/pull/1187) fix:payment refundable update
N/A.
* changelog

docs: release: draft release for v1.0.1

---

cmd/command/cmd_wrapper.go
cmd/command/config.go
cmd/command/debug.go
cmd/command/debug_test.go
cmd/command/exit_migrate.go
cmd/command/exit_migrate_test.go
cmd/command/p2p.go
cmd/command/query.go
cmd/command/query_test.go
cmd/command/quota.go
cmd/command/recovery.go

Adjust SP commands description.
For better description format,
`./gnfd-sp list.modules -h`
* N/A

fix: adjust sp command description

---

base/gfspapp/approval_server.go
base/gfspapp/authenticator_server.go
base/gfspclient/authenticator.go
base/gfspclient/client.go
base/gfsprcmgr/scope.go
base/gfspvgmgr/virtual_group_manager.go
modular/approver/approve_task.go
modular/authenticator/off_chain_signer.go
modular/blocksyncer/blocksyncer_options.go
modular/executor/execute_task.go
modular/gater/admin_handler.go
modular/gater/object_handler.go
modular/gater/query_util.go
modular/manager/manager.go
store/piecestore/client/piece_store_client.go

Fix resource leak.
1.Resource manager deadlock can lead to resource leaks and requests getting stuck.
2.Authenticator client connection leak.
N/A.
* Manager: remove redundant db load function.
* Resource manager: fix deadlock.
* Authenticator: fix connection leak.
* Others: polish some log.

fix: fix resource leak

---

.github/workflows/docker-develop.yml
CHANGELOG.md
cmd/command/bs_data_migration/bs_data_migration.go
go.mod
go.sum
modular/gater/admin_handler.go
modular/gater/admin_handler_test.go
modular/gater/const.go
modular/gater/router.go
modular/gater/router_test.go
store/bsdb/object_schema.go

Sync master branch to develop branch
N/A.
N/A.
* N/A.

sync: sync master branch to develop branch

---

modular/gater/auth_handler.go
modular/gater/auth_handler_test.go

fix: return 400 when getting invalid header for getNonceAPI
N/A
if user request doesn't contain a domain, it should response with a 400 httpCode rather than 500:
``` sh
curl --location '127.0.0.1:9133/auth/request_nonce' \
--header 'X-Gnfd-User-Address: 0x3d0a49B091ABF8940AD742c0139416cEB30CdEe0'
< HTTP/1.1 400 Bad Request
<Error><Code>50017</Code><Message>The X-Gnfd-App-Domain header is incorrect.</Message></Error>%
```
* add domain/userAddress head parameter validation logic
* add UT

fix: return 400 when getting invalid header for getNonceAPI

---

base/gfspapp/app_options.go

Gateway module removes dependency on spdb.
N/A
N/A
* N/A

fix: gateway module removes dependency on spdb

---

CHANGELOG.md
base/gfspconfig/config.go
base/gfspvgmgr/sp_freeze_pool.go
base/gfspvgmgr/types.go
base/gfspvgmgr/virtual_group_manager.go
base/gfspvgmgr/virtual_group_manager_test.go
core/vgmgr/virtual_group_manager.go
docs/run-book/config/config_template.toml
modular/manager/bucket_migrate_scheduler.go
modular/manager/manage_task.go
modular/manager/manager.go
modular/manager/manager_options.go

chore: resolve conflict

---

README.md
docs/run-book/config/config_template.toml

Add probe config.
N/A
N/A
* N/A

docs: add probe config

---

base/gfspvgmgr/virtual_group_manager.go
go.mod
modular/executor/execute_replicate.go
modular/gater/admin_handler.go

The meta api might return nil result while there is no err. 
* ...
* ...

fix: queried gvg might be nil

---

CHANGELOG.md

chore: add change log

---

modular/gater/metadata_handler.go

Refine some logs.
N/A.
N/A.
* Gateway metadata handler log.
* N/A.

chore: refine some logs

---

base/gfspconfig/config.go
store/types/store.go

Refine config comment.
N/A.
N/A.
N/A.
N/A.

chore: refine config comment

---

base/gfspvgmgr/virtual_group_manager.go
core/spdb/entity.go
modular/gater/admin_handler.go
modular/manager/manage_task.go
modular/manager/recover_scheduler.go
store/sqldb/exit_recover.go
store/sqldb/exit_recover_schema.go

1. fix the offset while iterating objects in GVG.
2. Union recover pieces
3. whitelist recovers data from secondary SP as successor secondary
* ...
* ...

fix: fix sp exit

---

CHANGELOG.md
base/gfspvgmgr/virtual_group_manager.go
modular/manager/manage_task.go

sync master branch to develop
* ...
* ...

release: sync the master branch to develop

---

CHANGELOG.md

doc: add changelog

---

cmd/command/swap_in.go
modular/manager/manager.go
modular/manager/recover_scheduler.go

perf:query empty vgf recover process

---

modular/manager/recover_scheduler.go

fix recover scheduler offset
* ...
* ...

fix: recover scheduler offset

---

cmd/command/swap_in.go
modular/manager/manager.go
modular/manager/recover_scheduler.go

perf:sp exit cmd print

---

modular/manager/task_retry_scheduler.go

the gvg info will not be available when object is just uploaded, so when init the replicate task, it needs to first pick a GVG.
* ...
* ...

fix: fix gvg not exist

---

CHANGELOG.md
base/gfspvgmgr/sp_freeze_pool.go
base/gfspvgmgr/virtual_group_manager.go
deployment/localup/localup.sh
modular/gater/admin_handler.go
modular/gater/admin_handler_test.go
modular/manager/task_retry_scheduler.go

this PR is to sync develop with master 
* ...
* ...

sync master

---

base/gfspvgmgr/virtual_group_manager.go
modular/manager/manage_task.go

fix the health check concurrency issue.
* ...
* ...

fix: fix the health check

---

base/gfspvgmgr/virtual_group_manager.go
modular/manager/manage_task.go

fix health check concurrency issue
* ...
* ...

fix: fix health check

---

modular/manager/recover_scheduler.go

Due to objects are in small size, the frequency can be adjusted. 
* ...
* ...

fix: change recover job frequency

---

modular/manager/manager.go
modular/manager/recover_scheduler.go

fix sending complete swap in tx, should wait for all gvg within vgf completed. 
* ...
* ...

fix: fix send complete swap tx

---

CHANGELOG.md

fix:change log confilct

---

CHANGELOG.md

docs: add changelog (#1309)

---

go.mod
go.sum

upgrade chain version
N/A
N/A
* upgrade chain version
N/A

fix: upgrade chain version

---

go.mod
go.sum
modular/gater/admin_handler.go
modular/gater/admin_handler_test.go
modular/gater/errors.go
modular/gater/helper_test.go
modular/gater/object_handler.go
modular/gater/object_handler_test.go
util/string.go

release: prepare release for v1.4.0
N/A
N/A
* prepare release for v1.4.0
N/A

release: prepare release for v1.4.0

---

modular/manager/manager.go
modular/manager/manager_test.go

Upload_Done tasks loaded from DB do not have GVG info.
* ...
* ...

fix: Upload_Done task loaded from DB does not have GVG info.

---

modular/executor/execute_gc.go

fix gc issue, when object is deleted, and GVG is changed when resealed.
* ...
* ...

fix: fix gc

---

base/gnfd/gnfd_service.go
modular/gater/object_handler.go
modular/manager/manage_task.go
modular/manager/task_retry_scheduler.go
modular/uploader/upload_task.go

A sealed object might have **is_udpating** status. Adjustment needed.
* ...
* ...

fix: fix the status check

---

modular/blocksyncer/modules/permission/permission_handler.go

update action type map:
1. ACTION_UPDATE_OBJECT_CONTENT
2. ACTION_UPDATE_GROUP_INFO
blocksyncer/blocksyncer_indexer.go:77","msg":"failed to handle event","module":"permission","event":{"type":"greenfield.permission.EventPutPolicy","attributes":[{"key":"expiration_time","value":"null","index":true},{"key":"policy_id","value":"\"1759\"","index":true},{"key":"principal","value":"{\"type\":\"PRINCIPAL_TYPE_GNFD_ACCOUNT\",\"value\":\"0xB1E0e59D3B67a993304461e778a856d439107a62\"}","index":true},{"key":"resource_id","value":"\"54106\"","index":true},{"key":"resource_type","value":"\"RESOURCE_TYPE_BUCKET\"","index":true},{"key":"statements","value":"[{\"effect\":\"EFFECT_ALLOW\",\"actions\":[\"ACTION_UPDATE_BUCKET_INFO\",\"ACTION_DELETE_BUCKET\",\"ACTION_CREATE_OBJECT\"],\"resources\":[],\"expirat …

fix: update action type map

---

store/sqldb/object_integrity.go
store/sqldb/object_integrity_test.go

fix override duplicate checksum
* ...
* ...

fix: deletion on checksum not fully performed and fail to override duplicate checksum

---

modular/authenticator/authenticator.go

fix: check if BucketExtraInfo is nil
N/A
N/A
* fix: check if BucketExtraInfo is nil
* N/A

fix: check if BucketExtraInfo is nil

---

modular/gater/bucket_handler.go
modular/gater/const.go
modular/gater/router.go

SP will provide the API to query the recommended virtual group family id for creating bucket. 
* ...
* ...

feat: provide recommended vgf

---

go.mod
go.sum
modular/blocksyncer/modules/bucket/bucket_handle.go
modular/blocksyncer/modules/events/sp_events_handler.go
store/bsdb/event_cancel_migration_bucket_schema.go
store/bsdb/event_complete_migration_bucket_schema.go
store/bsdb/event_migration_bucket_schema.go
store/bsdb/event_reject_migrate_bucket_schema.go

add bucket status field for migrate event

feat: bs add bucket status field

---

modular/blocksyncer/modules/events/module.go

fix: bs bucket migrate event bug

---

base/gfspvgmgr/virtual_group_manager.go
pkg/metrics/metric_items.go

fix: check sp health metric
N/A
N/A
* fix: check sp health metric
*N/A

fix: metric check sp

---

base/gfspvgmgr/virtual_group_manager.go
base/gnfd/gnfd_service.go
go.mod
go.sum
modular/blocksyncer/blocksyncer_options.go

1. add timeout for blocksyncer rpc client
2. wait for next block failure does not return, maximum effort retry
3. reduce create gvg StakingStorageSize

perf: logic

---

base/gfspvgmgr/virtual_group_manager.go

fix: gvg staking storage size

---

base/gfspvgmgr/virtual_group_manager.go

fix: indentation
N/A
N/A
* fix: indentation
N/A

fix: indentation

---

modular/gater/object_handler.go

delegate interface add  visibilityInt value check logic

fix: visibilityInt value check

---

.github/workflows/docker-develop.yml
core/piecestore/piecestore.go
core/piecestore/piecestore_mock.go
modular/executor/execute_gc.go
modular/executor/executor_task_test.go
store/piecestore/client/piece_store_client.go
store/piecestore/storage/oss.go
store/piecestore/storage/s3.go

Bug fix and log updates after test on testnet oss/aws.
* ...
* ...

fix: gc objects
