bnb-chain/greenfield-storage-provider

- pkg/p2p/node.go
Add nat manager for p2p node.
In consideration of network security and deployment efficiency, need to be fixed the public IP and protect private ip. 
N/A
N/A
> feat: add nat manager for p2p

- pkg/p2p/node_config.go
- pkg/p2p/node_config_test.go
Support DNS for p2p bootstrap node
Use for k8s ALB and NLB
N/A
N/A
> feat: support dns for p2p node

- pkg/metrics/metric_items.go
- pkg/metrics/metrics.go
- service/tasknode/replicate_object_task.go
- service/tasknode/task_node_service.go
- store/sqldb/traffic.go
1. TaskNode service adds seal object metrics.
2. Refine the replicate task and add some DB logs.
N/A
N/A
* TaskNode/SQLDB.
> feat: adds seal object metrics and refine some codes

- proto/service/metadata/types/metadata.proto
- service/metadata/service/object.go
- store/bsdb/object.go
An additional response field `update_at` has been added, and data with the same `update_at` object will be sorted by object ID. 
N/A
N/A
* Update new response field update_at
* Same `update_at` object will be sorted by object ID.
> feat: update schema and order for list deleted objects

- Makefile
- model/const.go
- service/downloader/downloader_service.go
- service/gateway/auth_handler.go
- service/gateway/auth_handler_test.go
- service/gateway/request_util_test.go
- service/metadata/service/object.go
Change the current off-chain-auth key update msg to EIP-4361 template
Though we are not implementing EIP-4361, it would be better use its msg template
The unsigned message presenting to end users will look like this:
```
https://greenfield.dapp.sample.io wants you to sign in with your BNB Greenfield account:
0xa64FdC3B4866CD2aC664998C7b180813fB9B06E6
Register your identity public key 4db642fe6bc2ceda2e002feb8d78dfbcb2879d8fe28e84e02b7a940bc0440083
URI: https://greenfield.dapp.sample.io
Version: 1
Chain ID: 5600
Issued At: 2023-04-18T16:25:24Z
Expiration Time: 2023-04-24T16:25:24Z
Resources:
- SP 677265656e6669656c642d73746f726167652d70726f7669646572 (name: SP_001) with nonce: 8
- SP 0x20Bb76D063a6d2B18B6DaBb2aC985234a4B9eDe0 (name: SP_002) with nonce: 1
```
* template …
> fix: use EIP-4361 message template for off-chain-auth

- .github/workflows/build-test.yml
- .github/workflows/code-lint.yml
- .github/workflows/commit-lint.yml
- .github/workflows/e2e-test.yml
- .github/workflows/gosec.yml
- .github/workflows/proto-lint.yml
- .github/workflows/unit-test.yml
- Dockerfile
- README.md
- config/config.go
- service/gateway/helper_test.go
- service/gateway/request_util.go
- service/gateway/request_util_test.go
- service/gateway/router_test.go
- service/metadata/service/object.go
- test/e2e/localup_env/greenfield_sp_env/sp0/config.toml
- test/e2e/localup_env/greenfield_sp_env/sp1/config.toml
- test/e2e/localup_env/greenfield_sp_env/sp2/config.toml
- test/e2e/localup_env/greenfield_sp_env/sp3/config.toml
- test/e2e/localup_env/greenfield_sp_env/sp4/config.toml
- test/e2e/localup_env/greenfield_sp_env/sp5/config.toml
- test/e2e/localup_env/greenfield_sp_env/sp6/config.toml
1. Permit anonymous users to access the public object.
2. Refine some config to ensure to run action checker.
This should be allowed if the HTTP request has no `Authorization` header and gets the public object. And this change depends on the VerifyPermission interface behavior of the chain, and the chain needs to be upgraded at the same time.
Refer to: https://github.com/bnb-chain/greenfield/pull/186
N/A
* Gateway.
> fix: permit anonymous users to access public object

- util/grpc/retry.go
Delete rpc timeout time.
N/A
N/A
N/A
> fix: delete rpc timeout time

- go.mod
- go.sum
- service/blocksyncer/block_syncer_indexer.go
Fix blocksyncer events handle failure, if failed, blocksyncer will retired until success
As we cannot let any errors go when it happens when handling an event, so we catch every error when export events
N/A
* add err handling when export and event failed
> fix: keep retrying when any blocksycner event handles failure

- model/const.go
- service/gateway/object_handler.go
Fix universal endpoint download as attachment 
For frontend correct download purpose 
Universal endpoint return ContentDispositionHeader as attachment 
* Downloader
> fix: universal endpoint attachment

- service/gateway/object_handler.go
- service/metadata/service/object.go
Fix universal endpoint cannot handle space in object name issue
Universal endpoint should support space and other escaped characters in object name
https://gf-sp-a.bk.nodereal.cc/download/rickie12/image (6).png -> in url become
https://gf-sp-a.bk.nodereal.cc/download/rickie12/image%20(6).png
shall be handled correctly with %20.
* Downloader
> fix: universal endpoint space

- service/gateway/object_handler.go
Use PathUnescape instead of QueryUnescape
to handle + unescape correctly 
N/A
* Downloader
> fix: use PathUnescape instead of QueryUnescape

- store/bsdb/object.go
fix sql parenthesis handling for get object
for get object method to return correctly 
N/A
* Metadata Service
> fix: sql paramthesis handling

- store/bsdb/object.go
fix sql parenthesis handling for get object
for get object method to return correctly 
N/A
* Metadata Service
> fix: sql parenthesis handling

- service/gateway/admin_handler.go
Not logging the err when `Unmarshal GetApproval Message`, it causing troubleshooting difficult. 
improving troubleshoot
NA
* NA
> fix: refine error log when Unmarshal failed

- go.mod
- go.sum
block syncer ignore group creation when no members included 
It's allowed when a group created with no members included, we return an error before, in this PR we fixed this and let it go
N/A
* relative changes updated in juno
> fix: block syncer ignore group creation when no members included

- model/const.go
- service/gateway/object_handler.go
- service/gateway/router.go
Add view option for universal endpoint and fix download file name without suffix
Users want to have a view option for universal endpoint, such that if they host html file on Dcellar, the universal endpoint will open the html in a new page other than download it as an attachment.
Universal Endpoint View link is like:
{endpoint}/view/{bucket_name}/{object_name}
* Add new Universal Endpoint api in Downloader
> feat: add universal endpoint view option 

- model/const.go
- service/gateway/object_handler.go
- service/gateway/router.go
Add view option for universal endpoint and fix download file name without suffix
Users want to have a view option for universal endpoint, such that if they host html file on Dcellar, the universal endpoint will open the html in a new page other than download it as an attachment.
Universal Endpoint View link is like:
{endpoint}/view/{bucket_name}/{object_name}
* Add new Universal Endpoint api in Downloader
> feat: add universal endpoint view option

- pkg/p2p/node.go
- pkg/p2p/node_config.go
- pkg/p2p/ping.go
- service/gateway/object_handler.go
- service/tasknode/replicate_object_task.go
- service/tasknode/stream_replicate_object_task.go
- service/tasknode/task_node_service.go
Add full-memory replicate task.
There are currently two replicate task implementations, full memory and streaming. Streaming takes up less memory, but in complex network conditions, the transmission is slower. The specific reason needs to be further located and optimized in the future. Full memory takes up more memory, but the transmission is faster, and full memory is used by default.
N/A.
* p2p: reduce debug log.
* gateway: fix invalid header.
* tasknode: add full-mem replicate task.
> feat: add full-memory replicate task

- pkg/p2p/node.go
- pkg/p2p/node_config.go
- pkg/p2p/ping.go
- service/gateway/object_handler.go
- service/tasknode/replicate_object_task.go
- service/tasknode/stream_replicate_object_task.go
- service/tasknode/task_node_service.go
Add full-memory replicate task, which is cherry-picked from [fix-release-v0.1.2](https://github.com/bnb-chain/greenfield-storage-provider/tree/fix-release-v0.1.2).
There are currently two replicate task implementations, full memory and streaming. Streaming takes up less memory, but in complex network conditions, the transmission is slower. The specific reason needs to be further located and optimized in the future. Full memory takes up more memory, but the transmission is faster, and full memory is used by default.
N/A.
* p2p: reduce debug log.
* gateway: fix invalid header.
* tasknode: add full-mem replicate task.
> feat: support full-memory replicate task

- config/config.go
fix nil db config error 
When I run it locally, there's no issue. However, when I run 7 service providers (sp) locally, the configuration file's metadata doesn't assign values to the 'bsdb' and 'switched db' within each service provider's 'config.toml'.
```
bash deployment/localup/localup.sh --stop
bash deployment/localup/localup.sh --generate /Users/barry/testbarry/greenfield-storage-provider/deployment/localup/sp.json root root1234 localhost:3306
bash deployment/localup/localup.sh --reset
bash deployment/localup/localup.sh --start
```
*  add db config in config.go
> fix:  fix nil pointer and update db config

- config/config.go
- config/subconfig.go
- go.mod
- go.sum
- pkg/middleware/http/tokenBucket.go
- service/gateway/gateway.go
- service/gateway/gateway_config.go
- service/gateway/object_handler.go
Upload and download with broadband stream implementation
Protect the sp service
Limit the upload and download speed
* Upload and download with broadband stream implementation
> feat:add upload download add bandwidth limit

- .github/workflows/e2e-test.yml
- service/gateway/object_handler.go
upgrade e2e ci greenfield version to v0.2.0
N/A
N/A
N/A
> fix: upgrade e2e ci greenfield version to v0.2.0

- go.mod
- go.sum
- service/metadata/service/object.go
- store/bsdb/object.go
fix: data query issues caused by character set replacement
N/A
N/A
* fix the query sql
* fix potential array index goes out of bounds bug
> fix: data query issues caused by character set replacement

- base/gfspconfig/config.go
- modular/p2p/p2p_options.go
- modular/p2p/p2pnode/node.go
- modular/p2p/p2pnode/node_options.go
- modular/p2p/p2pnode/ping.go
Add p2p ant config, response will parser self ant address to multiaddr to sync.
N/A
N/A
N/A
> feat: add p2p ant address config

- store/bsdb/common.go
- store/bsdb/object.go
fix listobjects sql error
N/A
N/A
* update listobjects sql
> fix: fix listobjects sql err

- base/gfspapp/app_options.go
Fix new piece store and spdb temporarily. This problem will be solved in the future.
N/A
N/A
N/A
> fix: fix new piece store and spdb

- go.mod
- go.sum
blocksyncer changes index type(object table) from unique to normal for object recreate scenario
blocksyncer uses unique union index(bucketname-objectname) while ignored the scenario that an object can be recreated with the same name after deletion. we fix this in this PR with juno version updated.
N/A
*  juno version updated with DB index type changed
> fix: blocksyncer fix data index with juno version update

- modular/metadata/metadata_options.go
let metadata only retrieve switch db signal from block syncer master db
N/A
N/A
* let metadata only retrieve switch db signal from block syncer master db
> fix: switchdb

- base/gfsppieceop/pieceop.go
There is an infinite loop of calls to this function of the ChallengePieceKey
fix bug
NA
* fix ChallengePieceKey
> fix: fix challenge piece key function

- base/gfsppieceop/pieceop.go
There is an infinite loop of calls to this function of the ChallengePieceKey
fix bug
NA
* fix ChallengePieceKey
> fix: fix  challengePieceKey function

- modular/metadata/metadata_options.go
add default db switch interval
N/A
* add default db switch interval
> fix: add default db switch interval

- service/gateway/object_handler.go
Fixing issue for get object meta info from incorrect source
* downloader (universal endpoint)
> fix: getObjectInfo from correct source

- base/gfspclient/metadata.go
- core/bsdb/metadata.go
- modular/approver/approve_task.go
- modular/gater/metadata_handler.go
- modular/metadata/metadata_bucket_service.go
- modular/metadata/metadata_group_service.go
- modular/metadata/metadata_object_service.go
- modular/metadata/metadata_payment_service.go
- modular/metadata/metadata_permission_service.go
- proto/modular/metadata/types/metadata.proto
- store/bsdb/bucket.go
- store/bsdb/database.go
- store/bsdb/database_mock.go
- store/bsdb/group.go
- store/bsdb/object.go
- store/bsdb/payment.go
- store/bsdb/permission.go
Adding "removed" param for metadata service apis 
1. For metadata service apis returning single object, we default removed = false into the db query 
2. For metadata service apis returning a list, we add input param "removed" for users to filter the list
N/A
> feat: add removed param for metadata service apis

- go.mod
- go.sum
group cannot be created when no members included in blocksyncer, while this is inconsistent with chain side.
This PR fix this by update juno version.
Keep group creation logic consistent with chain side
N/A
* juno version updated
> fix: update juno version for group creation logic fix

- go.mod
- go.sum
group cannot be created when no members included in blocksyncer, while this is inconsistent with chain side.
This PR fix this by update juno version.
Keep group creation logic consistent with chain side
N/A
* juno version updated
> fix: update juno version to fix group handler when no members included 

- base/gnfd/gnfd_service.go
- modular/approver/approve_task.go
- modular/executor/execute_task.go
- modular/gater/admin_handler.go
- pkg/metrics/metric_items.go
Add more metrics to perf get approval, which is cherry-picked from https://github.com/bnb-chain/greenfield-storage-provider/pull/573.
N/A.
N/A.
* Add the greenfield chain metrics and get approval workflow metrics.
> perf: add more metrics to perf get approval v0.2.2

- go.mod
- go.sum
Fix compile warnings.
Update the dependency version to fix the below warning.
`
greenfield-storage-provider % make build
bash +x ./build.sh
github.com/rjeczalik/notify
cgo-gcc-prolog:217:2: warning: 'FSEventStreamScheduleWithRunLoop' is deprecated: first deprecated in macOS 13.0 - Use FSEventStreamSetDispatchQueue instead. [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:1138:1: note: 'FSEventStreamScheduleWithRunLoop' has been explicitly marked deprecated here
build succeed!
`
N/A.
* Update rjeczalik/notify version to fix compile warnings.
> build: fix compile warning

- modular/executor/execute_task.go
- modular/manager/manager_options.go
Modify the default gc opt to a suitable value which is cherry-picked from https://github.com/bnb-chain/greenfield-storage-provider/pull/613.
Previously, a gc task of 500 blocks was generated every half hour, but the blockchain generated 900 blocks every half hour; resulting in the gc task not being able to keep up with the latest high speed.
N/A.
* Manager default opt.
> fix: modify the default gc opt to a suitable value v0.2.2

- modular/executor/execute_task.go
- modular/manager/manager_options.go
Modify the default gc opt to a suitable value.
Previously, a gc task of 500 blocks was generated every half hour, but the blockchain generated 900 blocks every half hour; resulting in the gc task not being able to keep up with the latest high speed.
N/A.
* Manager default opt.
> fix: modify the default gc opt to a suitable value

- modular/executor/execute_task.go
Fix missing gc object, which is cherry-picked from https://github.com/bnb-chain/greenfield-storage-provider/pull/621.
When objects are in different blocks, object ids are unordered. The check order may cause some objects not to be gc.
N/A.
* GC object workflow, fix check conditions.
> fix: fix missing gc object v0.2.2

- modular/executor/execute_task.go
Fix missing gc object.
When objects are in different blocks, object ids are unordered. The check order may cause some objects not to be gc.
N/A.
* GC object workflow, fix check conditions.
> fix: fix missing gc object

- modular/signer/signer_client.go
```
{"t":"2023-06-21T06:57:28.625Z","l":"error","caller":"signer/signer_client.go:353","msg":"failed to get seal account nonce","error":"request cannot be nil: invalid request","errorVerbose":"\ngithub.com/cosmos/cosmos-sdk/client.Context.Invoke\n\t/go/pkg/mod/github.com/bnb-chain/greenfield-cosmos-sdk@v0.2.2-alpha.1/client/grpc_query.go:42\ngithub.com/cosmos/cosmos-sdk/client/grpc/tmservice.(*serviceClient).GetLatestBlock\n\t/go/pkg/mod/github.com/bnb-chain/greenfield-cosmos-sdk@v0.2.2-alpha.1/client/grpc/tmservice/query.pb.go:1348\ngithub.com/bnb-chain/greenfield-storage-provider/modular/signer.latestBlockHeight\n\t/greenfield-storage-provider/modular/signer/signer_client.go:435\ngithub.com/bnb-chain/greenfield-storage-provider/modular/signer.waitForNextBlock\n\t/greenfield-storage-provi …
```
> fix: request cannot be nil in latestBlockHeight

- base/gfsppieceop/pieceop.go
This pr will add a different prefix for the segment and ec piece key.
The reason is if we add a different prefix for the segment and ec piece key, we can add filter by prefix for the segments and ec chunks stored in s3 and we can apply different rules to save cost (ie, we can store the segments in intelligent tierring which is more expensive, and store the ec chunks in glacier which is cheaper). Another reason is that s3 doesn't allow regex for the prefix, so we need to add a prefix for the stored pieces.
This change allows us to store all the pieces in one bucket and we don't need to create multiple buckets for the cost saving.
n/a
* add prefix for segment and ec piece key
> feat: add prefix for segment and ec piece key

- modular/signer/signer_client.go
This pr will simulate discontinue bucket transaction before broadcasting.
To save costs if there is lag in metadata service.
NA
* add simulation
> feat: simulate discontinue transaction before broadcast

- base/gnfd/gnfd.go
- go.mod
- util/rpc/jsonrpc/client/http_json_client.go
feat: customize http client using connection pool
> feat: customize http client using connection pool

- go.mod
- go.sum
blocksyncer adapt latest changes for sp meta from chain side
sp data structure chaged(replace operatore address with spId), we adapted this change in juno and this PR is to update dependency
N/A
*  juno version updated
> feat:  blocksyncer adapt latest changes for sp meta from chain side( with juno version updated)

- go.mod
- go.sum
- modular/blocksyncer/modules/events/sp_events_handler.go
- store/bsdb/event_swap_out_schema.go
change spIds type from String[] to Unit32[]
It's easier for metadata to query with "FIND IN SET" 
N/A
* change spIds type from String[] to Unit32[] with juno version updated
> fix: update juno with 'spIds' type change

- modular/downloader/download_task.go
- modular/downloader/downloader_options.go
- modular/gater/object_handler.go
remove challenge recovery condition.  If calling PieceStore().GetPiece got an error in the download task,  it is the ErrPieceStore, no need to judge the inner code.
inner code error is not supported  in download task when calling PieceStore().GetPiece
NA
* remove challenge recovery condition
> fix: fix challenge recovery

- modular/downloader/download_task.go
- modular/downloader/downloader_options.go
- modular/gater/object_handler.go
remove challenge recovery condition. If calling PieceStore().GetPiece got an error in the download task, it is the ErrPieceStore, no need to judge the inner code.
inner code error is not support in download task when call pieceStore.getPiece(). 
NA
* remove challenge recovery condition
> fix: fix challenge recovery 

- .github/workflows/e2e-test.yml
- .github/workflows/generate-private-key.js
- test/e2e/spworkflow/e2e_test.sh
remove the private_key from the code
We should not keep the private key in the code , even it is for test purpose
* generate the private key by using ether js package
* put the generated private key and account address into the e2e test action setp
> fix: remove the private_key from the code

- modular/blocksyncer/database/database.go
- modular/blocksyncer/database/object.go
- modular/blocksyncer/database/objectidmap.go
- modular/blocksyncer/database/prefixtree.go
- modular/blocksyncer/modules/object/module.go
- modular/blocksyncer/modules/object/object_handler.go
- modular/blocksyncer/modules/objectidmap/module.go
- modular/blocksyncer/modules/objectidmap/object_id_map.go
- modular/blocksyncer/modules/prefixtree/prefix_tree.go
- modular/blocksyncer/modules/registrar.go
- modular/gater/router.go
- modular/metadata/metadata.go
- modular/metadata/metadata_options.go
- store/bsdb/const.go
- store/bsdb/object.go
- store/bsdb/object_id_map.go
- store/bsdb/object_id_map_schema.go
- store/bsdb/prefix.go
- store/sqldb/object_integrity.go
- store/sqldb/object_integrity_schema.go
- store/sqldb/store.go
Sharding for SP database tables which include:
BSDB: object, slash_prefix_tree_nodes
SPDB: object_integrity
Each of the above tables will be sharded to 64 tables.
We want to optimize the query speed with no breaking change, before the Mainnet get launched. After the Mainnet launch, the object size will soon exceed 5,000,000 lines, which would degrade Mysql performance.
None of the API usage shall feel any difference. The changes are made in the db level.
* bsdb
* spdb
> feat: SP database sharding

- modular/gater/object_handler.go
Let getObject's offchain-auth support query params along with headers.
For more convenient frontend/browser access when downloading objects through offchain-auth
curl --location 'https://gf-stagenet-sp-h.bk.nodereal.cc/test-sp-7/flower1.webp?Authorization=OffChainAuth%20EDDSA%2CSignedMsg%3DInvokeSPAPI_offChainSign_1689077696938%2CSignature%3De931ee622e73053aeef2ffe347ca28d9cd2f8017c2eb0c84b6afbdf04d6bcf9b047a246c965e41102235b620e918d0bc40b64e151b5ed2d498b6efe548a89d3f&X-Gnfd-User-Address=0x06B320Cd13BAe882AA446F814aA659ed0923d1e1&X-Gnfd-App-Domain=https%3A%2F%2Fdcellar-qa.fe.nodereal.cc' --output image.jpg
* downloader
> feat: support query params for getObject off-chain auth

- modular/authenticator/authenticator.go
The logic of checking the existence of the account has been removed from the VerifyAuthentication function which is used to verify authorization of the request to SP.  The reasons for the removal are as follows:：
1）Data marketplace users only operate on BSC and have no transactions on Greenfield.
2）During batch upload, a temporary account is generated, and the gas and fees for this temporary account are deducted from the user's account (with authorization). This temporary account has not yet been created on the chain, but actions like createObject are performed
support marketplace user case
NA
*  remove checking the existence of the account
> fix: fix authenticator 

- modular/authenticator/authenticator.go
The logic of checking the existence of the account has been removed from the VerifyAuthentication function which is used to verify authorization of the request to SP.  The reasons for the removal are as follows:：
1）Data marketplace users only operate on BSC and have no transactions on Greenfield.
2）During batch upload, a temporary account is generated, and the gas and fees for this temporary account are deducted from the user's account (with authorization). This temporary account has not yet been created on the chain, but actions like createObject are performed
support marketplace user case
NA
*  remove checking the existence of the account
> fix: remove checking account if it is exists in greenfield

- modular/blocksyncer/database/object.go
Fix block syncer copy object after introduce sharding
Sharding introduce a bug when try to use object bucketname that has not yet created
N/A
* block syncer
> fix: block syncer copy object

- modular/gater/admin_handler.go
- modular/gater/bucket_handler.go
- modular/gater/const.go
- modular/gater/metadata_handler.go
- modular/gater/object_handler.go
- modular/gater/request_context.go
remove v2 Authorization
1. metadata apis will not require authorization
2. object/admin/bucket handler will remove SkipVerifyAuthentication
N/A
N/A
* remove v2 Authorization
> fix: remove v2

- store/sqldb/const.go
- store/sqldb/store.go
- store/sqldb/util.go
As there are scenarios where multiple pods start together, it is possible when we cleanup spdb and recreate tables with autoMigrate, there will be race condition when creating a table which another pod just created, thus throw an error. We want to silent such "table already exists" error to not throw and return nil db pointer, but continue execution onto the next table.
spdb init db logic update.
N/A
* spdb
> fix: handle concurrent spdb table creation

- base/gfspclient/metadata.go
- modular/gater/const.go
- modular/gater/metadata_handler.go
- modular/gater/router.go
- modular/gater/router_test.go
- modular/metadata/metadata_permission_service.go
- proto/modular/metadata/types/metadata.proto
- store/bsdb/database.go
- store/bsdb/group.go
- store/bsdb/object.go
support object/bucket/group verify permission
N/A
```
curl --location --request GET 'http://localhost:9133/?verify-id=&resource-id=1&resource-type=3&operator=0xB6e0Fc49DA3C0bD76aF9851Fc36589306f034583&action-type=9'
```
*support object/bucket/group verify permission
> feat: support verify permission by id

- base/gfspclient/metadata.go
- modular/gater/const.go
- modular/gater/metadata_handler.go
- modular/gater/router.go
- modular/gater/router_test.go
- modular/metadata/metadata_permission_service.go
- proto/modular/metadata/types/metadata.proto
- store/bsdb/database.go
- store/bsdb/group.go
- store/bsdb/object.go
support object/bucket/group verify permission
N/A
```
curl --location --request GET 'http://localhost:9133/?verify-id=&resource-id=1&resource-type=3&operator=0xB6e0Fc49DA3C0bD76aF9851Fc36589306f034583&action-type=9'
```
*support object/bucket/group verify permission
> fix: verify group permission

- CHANGELOG.md
draft release for v0.2.3-alpha.7.
FEATURES
* [#824](https://github.com/bnb-chain/greenfield-storage-provider/pull/824) feat: support sp exit and bucket migrate
* [#856](https://github.com/bnb-chain/greenfield-storage-provider/pull/856) feat: update local virtual group event
* [#853](https://github.com/bnb-chain/greenfield-storage-provider/pull/853) feat: update greenfield-go-sdk e2e version
* [#852](https://github.com/bnb-chain/greenfield-storage-provider/pull/852) ci: fix docker-ci.yml to push develop
* [#865](https://github.com/bnb-chain/greenfield-storage-provider/pull/865) feat: add bucket migrate & sp exit query cli
BUGFIX
* [#834](https://github.com/bnb-chain/greenfield-storage-provider/pull/834) fix: remove v2 Authorization
* …
> release: draft release for v0.2.3-alpha.7

- modular/gater/const.go
- modular/gater/object_handler.go
- modular/gater/router.go
Fix issue where pdf and xml private universal endpoint not compatible with metamask plugin by changing to special url.
N/A
https://gnfd-testnet-sp-3.bnbchain.org/download/articles/whale.pdf ->
https://gnfd-testnet-sp-3.bnbchain.org/download?objectPath=articles/whale.pdf
* object handler
* router
> fix: private universal endpoint special suffix handle

- base/gfspapp/sign_server.go
- base/gfspclient/metadata.go
- base/gfspclient/signer.go
- base/gnfd/gnfd_service.go
- cmd/command/quota.go
- cmd/storage_provider/main.go
- core/consensus/consensus.go
- core/module/modular.go
- core/module/null_modular.go
- core/spdb/entity.go
- core/spdb/spdb.go
- core/spdb/spdb_mock.go
- modular/downloader/download_task.go
- modular/gater/bucket_handler.go
- modular/metadata/metadata_bucket_service.go
- modular/metadata/metadata_options.go
- modular/signer/signer.go
- modular/signer/signer_client.go
- proto/base/types/gfspserver/sign.proto
- proto/modular/metadata/types/metadata.proto
- store/sqldb/traffic.go
- store/sqldb/traffic_schema.go
- test/e2e/spworkflow/e2e_test.sh
1. change the algorithm of quota consumption
The freeQuota will no longer be reset and updated monthly. Instead, it will be fixed based on the value on the chain, and once it is fully consumed, it will not be available anymore.
3. support commands to update free quota
SP can use the command to update his free quota on greenfield
improve the way of quota consume
NA
* update quota consumption method
> refactor:  update quota consumption method

- CHANGELOG.md
Draft release for v0.2.3-alpha.11.
FEATURES
* [#867](https://github.com/bnb-chain/greenfield-storage-provider/pull/867) feat: impl ListObjectsByGVGAndBucketForGC and object details
* [#888](https://github.com/bnb-chain/greenfield-storage-provider/pull/888) feat: metadata and block syncer monitor
* [#890](https://github.com/bnb-chain/greenfield-storage-provider/pull/890) feat: add generate gvg sp policy
* [#851](https://github.com/bnb-chain/greenfield-storage-provider/pull/851) feat: support query sp
REFACTOR
* [#860](https://github.com/bnb-chain/greenfield-storage-provider/pull/860) refactor: update quota consumption method
BUGFIX
* [#848](https://github.com/bnb-chain/greenfield-storage-provider/pull/848) fix: fix recover command
* …
> release: draft release for v0.2.3-alpha.11

- modular/gater/object_handler.go
After refactor, the escape of object name is already done in reqContext, and doing it one more time might cause error. Thus removing the duplicate.
N/A
N/A
* object handler (universal endpoint)
> fix: universal endpoint escape

- modular/metadata/metadata_bucket_service.go
- modular/metadata/metadata_sp_exit_service.go
return err when request block id is larger than latest block height for  swapout/spexit/mirgration bucket event apis
N/A
N/A
* return err when request block id is larger than latest block height for  swapout/spexit/mirgration bucket event apis
> fix: return err when block height > latest

- modular/metadata/metadata_bucket_service.go
- modular/metadata/metadata_sp_exit_service.go
return err when request block id is larger than latest block height for  swapout/spexit/mirgration bucket event apis
N/A
N/A
* return err when request block id is larger than latest block height for  swapout/spexit/mirgration bucket event apis
> fix: return err when request height > latest

- modular/manager/bucket_migrate_scheduler.go
pick sp gvg not exiting.
During the bucket migration process, we have a source Global Virtual Group (GVG) with a list of members [3, 1, 2, 4, 5, 6, 7]. The goal is to organize the destination GVG by replacing any member from the source GVG that is in STATUS_GRACEFUL_EXITING.
To achieve this, we compare the members of the source GVG with the destination GVG. If we find a member from the source GVG that is in STATUS_GRACEFUL_EXITING, we replace it in the destination GVG. 
* ...
> feat: pick sp gvg not exiting

- base/gfspclient/metadata.go
- core/spdb/spdb.go
- core/spdb/spdb_mock.go
- modular/gater/object_handler.go
- modular/metadata/metadata_sp_service.go
- proto/modular/metadata/types/metadata.proto
- store/sqldb/sp.go
Fix the mistakenly changed redirect logic of Universal Endpoint, to redirect to Bucket's endpoint, not own sp's endpoint.
As the structs changed and it is easier to get SpId of a bucket comparing with SpOperatorAddress, we also change metadata's method of getting SpEndpoint to input SpId directly, and add a new query in spdb for getting sp by spId. 
N/A
N/A
* object handler (universal endpoint)
> fix: universal endpoint redirect using bucket's real endpoint

- modular/executor/migrate_task.go
- modular/gater/migrate_handler.go
- modular/manager/bucket_migrate_scheduler.go
- modular/manager/sp_exit_scheduler.go
cherry-pick #917 
Fix when selecting the target sp, you can choose primary sp as the target gvg's secondary sp node.
NA
NA
* NA
* ...
> fix: release v0.2.3 pick sp can select primary sp(cherry-pick #917)

- store/piecestore/piece/piece_store.go
- test/e2e/piecestore/b2_test.go
- test/e2e/piecestore/disk_file_test.go
- test/e2e/piecestore/helper_test.go
- test/e2e/piecestore/memory_test.go
- test/e2e/piecestore/minio_test.go
- test/e2e/piecestore/s3_test.go
- test/e2e/piecestore/sharding_test.go
Optimize when failed to new piece store, invalid config or failed to head bucket, program will panic.
N/A
N/A
* N/A
> fix: failed to new piece store will panic

- modular/gater/object_handler.go
- modular/gater/router_test.go
Add content-disposition as attachment, so that he newly added query param auth method for off-chain auth can have consistent download experience with the existing header auth method.
Also add the unit tests of new apis introduced in https://github.com/bnb-chain/greenfield-storage-provider/pull/897
N/A
N/A
* object handler (getObject)
> fix: add content-disposition for off-chain download and tests for new apis

- modular/gater/object_handler.go
- modular/gater/router_test.go
Add content-disposition as attachment, so that he newly added query param auth method for off-chain auth can have consistent download experience with the existing header auth method.
Also add the unit tests of new apis introduced in https://github.com/bnb-chain/greenfield-storage-provider/pull/897
N/A
N/A
* object handler (getObject)
> fix: add content-disposition for off-chain download 

- base/gfspvgmgr/virtual_group_manager.go
- modular/manager/bucket_migrate_scheduler.go
- modular/manager/sp_exit_scheduler.go
refactor bucket migration and fix some bugs
* Reorganized the process of subscribeEvents. Upon receiving `CancelEvents` and `CompleteEvents`, they are removed from the `executePlanIDMap` in memory.
* If multiple MigrationBucketEvents are received consecutively, it is considered that the bucket is migrating, and the second event is rejected.
* The background process will repeatedly attempt to process any ongoing MigrationBucketEvents until they are either completed or canceled.
* When loading BucketMigrateExecutePlans, construction is skipped if there are CancelEvents or CompleteEvents.
NA
* NA
* ...
> refactor : migrate bucket fix v0.2.3

- modular/metadata/metadata_sp_exit_service.go
filter complete migration buckets from ListMigrateBucketEvents api
N/A
N/A
* filter complete migration buckets from ListMigrateBucketEvents api
> fix: filter complete migration buckets

- base/gfspclient/metadata.go
- modular/gater/metadata_handler.go
- modular/manager/sp_exit_scheduler.go
- modular/metadata/metadata_sp_exit_service.go
- proto/modular/metadata/types/metadata.proto
- store/bsdb/database.go
- store/bsdb/event_sp_exit.go
replace operator address to sp id for list sp exit event api
N/A
N/A
* replace operator address to sp id for list sp exit event api
> fix: replace operation address to sp id sp exit

- modular/gater/const.go
- modular/gater/object_handler.go
Fix the issue for content-disposition where it used reqCtx before it has value. Also update query params' naming and add "view" as optional query param to switch content-disposition from default download to view.
N/A
N/A
* object handler
> fix: offchain-auth content-disposition and query param changes

- base/gfspapp/task_options.go
- base/types/gfsptask/task.pb.go
- modular/executor/migrate_task.go
- modular/gater/admin_handler.go
- modular/manager/manage_task.go
- modular/manager/manager.go
- modular/manager/sp_exit_scheduler.go
- pkg/metrics/metric_items.go
Refine migrate gvg task workflow.
1. Infinitely retry migration tasks in case of failure, only be gc when it is finished.
2. When the task is not updated within a certain period of time, it will be executed by other executors.
N/A.
* Refine migrate gvg task retry policy and gc policy.
* Refine some log and add metrics.
> fix: refine migrate gvg task workflow

- pkg/pprof/pprof.go
- allocs      : "A sampling of all past memory allocations"
- block       : "Stack traces that led to blocking on synchronization primitives"
- goroutine   : "Stack traces of all current goroutines. Use debug=2 as a query parameter to export in the same format as an unrecovered panic."
- heap        : "A sampling of memory allocations of live objects. You can specify the gc GET parameter to run GC before taking the heap sample."
- mutex       : "Stack traces of holders of contended mutexes"
- threadcreate: "Stack traces that led to the creation of new OS threads"
* ...
> fix: add missing path for pprof server

- base/gfspapp/sign_server.go
- base/gnfd/gnfd_service.go
- core/consensus/consensus.go
- core/consensus/consensus_mock.go
- core/module/modular.go
- core/module/null_modular.go
- core/spdb/spdb_mock.go
- modular/manager/sp_exit_scheduler.go
- modular/signer/signer.go
- modular/signer/signer_client.go
- modular/signer/signer_options.go
- store/bsdb/database_mock.go
Add tx confirm func and create virtual group retry.
Send tx and query tx hash, in order to ensure the tx executed by chain.
N/A.
* signer/chain client.
> feat: add tx confirm func and create virtual group retry

- modular/downloader/download_task.go
- store/sqldb/traffic.go
Ignore duplicate entry when create bucket traffic.
Ignore failures caused by concurrent updates.
N/A
* downloader.
> fix: ignore duplicate entry when create bucket traffic

- go.mod
- go.sum
- modular/gater/auth_handler.go
- modular/gater/const.go
- modular/gater/request_context.go
feat: rename personal sign
It was "PersonalSign ECDSA-secp256k1" and it is now renamed to "GNFD1-ETH-PERSONAL_SIGN"
> feat: rename personal sign auth name for updateKey API

- CHANGELOG.md
This release includes 4 features, 4 refactors, 9 bugfixes, and 3 test updates.
FEATURES
* [#857](https://github.com/bnb-chain/greenfield-storage-provider/pull/857) feat: validate virtual group families' qualification
* [#985](https://github.com/bnb-chain/greenfield-storage-provider/pull/985) feat:time Ticker
* [#981](https://github.com/bnb-chain/greenfield-storage-provider/pull/981) feat: add tx confirm func and create virtual group retry
* [#968](https://github.com/bnb-chain/greenfield-storage-provider/pull/968) feat: bucket migrate check when load from db
REFACTOR
* [#983](https://github.com/bnb-chain/greenfield-storage-provider/pull/983) refine: refactor bucket migrate code
* [#953](https://github.com/bnb-chain/greenfield-storage-provider/pull/953) Refactor manager that dispatch task …
> release: draft release for v0.2.4-alpha.1

- test/e2e/spworkflow/e2e_test.sh
Fix occasional compile error.
blst has problem in some old cpu, could cause SIGILL, and use environment variables for compatible configuration.
Compile error log:
```shell
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.
./deployment/localup/localup.sh: line 285: echo: write error: Broken pipe
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.
Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.
Error: Process completed with exit code 132.
``` 
Notable …
> fix: fix occasional compile error

- store/sqldb/traffic.go
- store/sqldb/traffic_test.go
- test/e2e/spworkflow/e2e_test.sh
update db update bucket traffic DB table by transaction
avoid db error when download objects using multiple threads
NA
* ...
> fix: db update bucket traffic by transaction

- base/gfspconfig/config.go
- cmd/command/exit_migrate.go
- cmd/storage_provider/main.go
- modular/executor/executor.go
- modular/executor/executor_options.go
- modular/executor/migrate_task.go
- modular/manager/bucket_migrate_scheduler.go
- modular/manager/migrate_unit.go
- modular/manager/sp_exit_scheduler.go
Fix bucket migrate workflow src gvg is overwritten.
Fix bucket migrate scheduler, from:
```go
srcSecondarySPIDs := srcGVG.GetSecondarySpIds()
``` 
to:
```go
srcSecondarySPIDs := make([]uint32, len(srcGVG.GetSecondarySpIds()))
copy(srcSecondarySPIDs, srcGVG.GetSecondarySpIds())
``` 
Avoid incorrectly modifying the gvg reference of proto in the context.
N/A.
* Refine the migrate struct field for printing friendly log.
* Add some cmd and conf for debugging.
> fix: fix src gvg is overwritten v0.2.4

- base/gfspconfig/config.go
- cmd/command/exit_migrate.go
- cmd/storage_provider/main.go
- modular/executor/executor.go
- modular/executor/executor_options.go
- modular/executor/migrate_task.go
- modular/manager/bucket_migrate_scheduler.go
- modular/manager/migrate_unit.go
- modular/manager/sp_exit_scheduler.go
Fix bucket migrate workflow src gvg is overwritten.
Fix bucket migrate scheduler, from:
```go
srcSecondarySPIDs := srcGVG.GetSecondarySpIds()
``` 
to:
```go
srcSecondarySPIDs := make([]uint32, len(srcGVG.GetSecondarySpIds()))
copy(srcSecondarySPIDs, srcGVG.GetSecondarySpIds())
``` 
Avoid incorrectly modifying the gvg reference of proto in the context.
N/A.
* Refine the migrate struct field for printing friendly log.
* Add some cmd and conf for debugging.
> fix: fix src gvg is overwritten

- modular/gater/metadata_handler.go
Changing all json response body to to xml, exclude the SP status api.
We want to unify the success response body and failure response body to all xml.
```
localhost:9133/cwtmcrfqen?bucket-meta
<GfSpGetBucketMetaResponse>
<Bucket>
<BucketInfo>
<Owner>0xB769053f37080e70EE8458B7d376cCD64C1d1eab</Owner>
<BucketName>cwtmcrfqen</BucketName>
<Visibility>2</Visibility>
<Id>1</Id>
<SourceType>0</SourceType>
<CreateAt>1688364497</CreateAt>
<PaymentAddress>0xB769053f37080e70EE8458B7d376cCD64C1d1eab</PaymentAddress>
<GlobalVirtualGroupFamilyId>0</GlobalVirtualGroupFamilyId>
<ChargedReadQuota>0</ChargedReadQuota>
<BucketStatus>0</BucketStatus>
</BucketInfo>
<Removed>false</Removed>
<DeleteAt>0</DeleteAt>
<DeleteReason></DeleteReason>
<Operator>0xB769053f37080e70EE8458B7d376cCD64C1d1eab</Operator> …
```
> feat: change json response body to xml

- modular/signer/signer_client.go
- modular/signer/signer_options.go
1. remove funding key in signer module
funding key is the more private key that should not be held by the app or dev.
N/A
* signer
> fix: remove funding key in singer module

- base/gnfd/gnfd_service.go
- cmd/command/cmd_wrapper.go
- cmd/command/config.go
- cmd/command/config_test.go
- cmd/command/debug.go
- cmd/command/debug_test.go
- cmd/command/exit_migrate.go
- cmd/command/exit_migrate_test.go
- cmd/command/p2p.go
- cmd/command/p2p_test.go
- cmd/command/query.go
- cmd/command/query_test.go
- cmd/storage_provider/main.go
- cmd/utils/init_env.go
Add cmd ut.
```shell
File coverage threshold (80%) satisfied:                FAIL
below threshold:                                      coverage:       threshold:
base/gfspapp/app.go                                   72%             80%
base/gfspapp/authenticator_server.go                  0%              80%
base/gfspapp/download_server.go                       0%              80%
base/gfspapp/manage_server.go                         0%              80%
base/gfspapp/p2p_server.go                            0%              80%
base/gfspapp/query_server.go                          0%              80%
base/gfspapp/rcmgr_server.go                          0%              80%
base/gfspapp/receive_server.go                        0%              80%
base/gfspapp/sign_server.go …
```
> test: add cmd ut

- modular/metadata/metadata_object_service.go
fix nil pointer err caused by ObjectDetails
```
/greenfield-storage-provider/store/bsdb/global_virtual_group.go:117
36
[392.420ms] [rows:1] SELECT * FROM `global_virtual_groups` WHERE global_virtual_group_id = 32 and removed = false LIMIT 1
35
{"t":"2023-08-23T03:18:24.339Z","l":"info","caller":"metadata/metadata_object_service.go:622","msg":"succeed to list objects by gvg id"}
34
panic: runtime error: invalid memory address or nil pointer dereference
33
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x141446c]
32
31
goroutine 186322 [running]:
30
github.com/bnb-chain/greenfield-storage-provider/modular/metadata/types.(*ObjectDetails).MarshalToSizedBuffer(0x0, {0xc00441a000, 0x16478, 0x16d7e})
29
/greenfield-storage-provider/modular/metadata/types/metadata.pb.go:7202 +0x2c …
```
> fix: nil pointer err caused by ObjectDetails

- base/gfspapp/app_options.go
signer module does not need spdb.
* ...
> fix: signer module does not need spdb

- modular/gater/object_handler.go
fix: set correct Content-Disposition when downloading an object
- remove incorrect  Content-Disposition header setting.
> fix: set correct Content-Disposition when downloading an object

- base/gfspclient/client.go
- modular/gater/gater.go
- modular/gater/router.go
- store/piecestore/storage/disk_file.go
- store/piecestore/storage/disk_file_test.go
- test/e2e/piecestore/sharding_test.go
* Accept
* Acknowledge
strconv.Atoi includes upper bound check
rand is not involved in the security of user data and user content   
GRPC is only used between internal services, no user requests
N/A
N/A
N/A
> fix: code security check

- cmd/command/recovery.go
- modular/executor/executor.go
1. Support recover object list 
2. fix counter bug of recover task
For the convenience of SP owner recover their accidentally deleted piece store.
./gnfd-sp recover.object -config config.toml -bucket gnfd-bucket -objectList testobject1 testobject2 ...
begin to recover the object of the primary SP: testobject1
succeed to gerate recovery object testobject1 task on background 
begin to recover the object of the primary SP: testobject2 
succeed to gerate recovery object testobject2 task on background 
* recovery command
> feat: recover object list

- modular/blocksyncer/modules/group/group_handler.go
- modular/metadata/metadata_permission_service.go
fix bug the group ExpirationTime is null
The group ExpirationTime may be empty
nothing
nothing
> feat:fix group ExpirationTime bug

- modular/gater/gater_options.go
- pkg/middleware/http/ratelimiter.go
fix: api rate limiter host pattern in sequence
Currently rate limiter api patterns are store in maps, which in golang maps are unsorted and resulting in iterate sequence difference every time, that might cause mismatch of regex patterns.
N/A
N/A
* api rate limiter
> fix: api rate limiter path sequence

- modular/metadata/metadata_bucket_service.go
- store/sqldb/traffic.go
- store/sqldb/traffic_schema.go
- store/sqldb/traffic_test.go
1. fix the return value of getUpdatedConsumedQuota function,  the order is wrong now
2. refactor quota table to support better get quota computing. The original way failed to get the right value of the consumed free quota of this month , and  need to query the table of last month to compute the consumed free quota of this month which cause more db operation
fix quota logic
```
[root@ localtest]# ./gnfd-cmd --passwordfile password.txt bucket get-quota gnfd://testbucket4
quota info:
charged quota:4476395008 
free quota:1344556800    // remained free quota
consumed quota:0 
free consumed quota: 4429185024 
[root@ localtest]# ./gnfd-cmd --passwordfile password.txt object get gnfd://testbucket4/dss5ds download2
download object dss5ds, the file path is download2, content length:1476395008 …
```
> fix: refactor quota table

- modular/metadata/metadata_bucket_service.go
- store/sqldb/traffic.go
- store/sqldb/traffic_schema.go
- store/sqldb/traffic_test.go
1. fix the return value of getUpdatedConsumedQuota function,  the order is wrong now
2. refactor quota table to support better get quota computing. The original way failed to get the right value of the consumed free quota of this month , and  need to query the table of last month to compute the consumed free quota of this month which cause more db operation
fix quota logic
```
[root@ localtest]# ./gnfd-cmd --passwordfile password.txt bucket get-quota gnfd://testbucket4
quota info:
charged quota:4476395008 
free quota:1344556800    // remained free quota
consumed quota:0 
free consumed quota: 4429185024 
[root@ localtest]# ./gnfd-cmd --passwordfile password.txt object get gnfd://testbucket4/dss5ds download2
download object dss5ds, the file path is download2, content length:1476395008 …
```
> fix :  refactor quota  table

- base/types/gfsptask/upload.go
- modular/executor/execute_replicate.go
fixes a issue that remaining jobs are not terminated if there is error during any replicating job.
* ...
> fix: stop all replicate jobs and done replicate job by canceling context

- CHANGELOG.md
Draft release for v0.2.5-alpha.2.
FEATURES
* [#1112](https://github.com/bnb-chain/greenfield-storage-provider/pull/1112) feat: support GfSpGetSPMigrateBucketNumber
BUGFIX
* [#1121](https://github.com/bnb-chain/greenfield-storage-provider/pull/1121) fix: fix tls MinVersion to 1.2
* [#1119](https://github.com/bnb-chain/greenfield-storage-provider/pull/1119) fix: stop all replicate jobs and done replicate job by context
* [#1117](https://github.com/bnb-chain/greenfield-storage-provider/pull/1117) fix: include private cause bucket not found
TEST
* [#1115](https://github.com/bnb-chain/greenfield-storage-provider/pull/1115) test: modular/gater pkg adds UTs part II
N/A.
* changelog
> docs: release: draft release for v0.2.5-alpha.2

- modular/metadata/metadata_options.go
Add back metadata go routine count listener
N/A
N/A
> feat: add back metadata go routine listener

- CHANGELOG.md
Draft release for v0.2.5-alpha.3.
FEATURES
* [#1129](https://github.com/bnb-chain/greenfield-storage-provider/pull/1129) feat: add back metadata go routine listener
* [#1128](https://github.com/bnb-chain/greenfield-storage-provider/pull/1128) feat: support expire time check of SP task info
BUGFIX
* [#1092](https://github.com/bnb-chain/greenfield-storage-provider/pull/1092) fix: support reimburse quota if download consumed extra quota
* [#1127](https://github.com/bnb-chain/greenfield-storage-provider/pull/1127) fix:bs groups unique index
* [#1125](https://github.com/bnb-chain/greenfield-storage-provider/pull/1125) fix: expiration time for statement
TEST
* [#1126](https://github.com/bnb-chain/greenfield-storage-provider/pull/1126) test: modular/executor pkg adds UTs
N/A.
* …
> docs: release: draft release for v0.2.5-alpha.3

- CHANGELOG.md
Draft release for v0.2.5.
BUGFIX
* [#1135](https://github.com/bnb-chain/greenfield-storage-provider/pull/1135) fix: effect allow issue
N/A.
* changelog
> docs: release: draft release for v0.2.5

- CHANGELOG.md
- store/bsdb/permission.go
Draft release for v0.2.5.
BUGFIX
* [#1135](https://github.com/bnb-chain/greenfield-storage-provider/pull/1135) fix: effect allow issue
N/A.
* changelog
> release: prepare release for v0.2.5

- base/types/gfsptask/upload.go
- modular/executor/execute_replicate.go
need to wait for all go-routines are done, becasue there are modification made by those routines even failure occur.
* ...
> fix: fix a  executor panic issue

- modular/blocksyncer/modules/permission/permission_handler.go
fix: policy statements is nil
Prevents service errors
nothing
nothing
> fix:policy statement is empty

- modular/gater/object_handler.go
fix: refactoring code for getObject and Universal apis
1. When returning 406 in getObject, the http connection was closed and causing go-sdk can't parse the response
2. In Universal endpoint, it used "download Object" API, which can take up lots of memory.  
3. Many logic code are duplicates in both getObject and Universal apis. In this PR, they are refined and organized into private method and shared by both apis.
* Remove unnecessary headers in error response
* Refactor  both getObject and Universal apis so that they can use the exact same download logic
> fix: refactoring code for getObject and Universal apis

- modular/receiver/receive_task.go
- modular/receiver/receive_task_test.go
- modular/uploader/upload_task.go
Currently, If uploaded object to SP does not match object meta created onchain, the SP does not handle the error and let replication to SSP happen, which should be restricted and also validation from secondary sp on receiving pieces must be performed to grantee consistence. 
Ensure data consistence
* ...
> fix: fix itegrity hash check

- CHANGELOG.md
Draft release for v0.2.6 alpha.2
BUGFIX
* [#1151](https://github.com/bnb-chain/greenfield-storage-provider/pull/1151) fix: update new logic of metadata apis
N/A.
* changelog
> docs:  draft release for v0.2.6-alpha.2

- modular/metadata/metadata_bucket_service_test.go
- modular/metadata/metadata_group_service_test.go
- modular/metadata/metadata_object_service_test.go
- modular/metadata/metadata_options_test.go
- modular/metadata/metadata_payment_service_test.go
- modular/metadata/metadata_permission_service_test.go
- modular/metadata/metadata_query_service_test.go
- modular/metadata/metadata_sp_exit_service.go
- modular/metadata/metadata_sp_exit_service_test.go
- modular/metadata/metadata_test.go
- store/bsdb/database_mock.go
add metadata api UT to 83.2% 
```
go test ./modular/metadata -coverprofile=coverage.out
ok      github.com/bnb-chain/greenfield-storage-provider/modular/metadata       1.175s  coverage: 83.2% of statements
```
N/A
N/A
* add metadata api UT
> test: add metadata api UT

- modular/gater/object_handler.go
- modular/gater/object_handler_test.go
add ut for universal endpoint handlers
* use r.URL.RequestURI() instead of r.RequestURI,  because in httptest.NewRequest the r.RequestURI value is the whole URL.
> fix: add ut for universal endpoint

- modular/executor/execute_task.go
- modular/gater/admin_handler.go
- modular/gater/errors.go
The previous way was to use integrity hash for verification of the recovered data , so there is not much risk .
This pr add checking to make sure the object is sealed when recovery object or pieces. Semantically speaking, only the seal object can be considered uploaded, so it can be not recovered if seal not finished.
add checking
NA
* ...
> fix: recovery object status should be sealed

- base/errors.md
- go.mod
- pkg/middleware/http/ratelimiter.go
fix: add xml response for rate limit error
Make rate limit error response format look consistent with other errors
```
curl -v 127.0.0.1:9133/auth/request_nonce
*   Trying 127.0.0.1:9133...
* Connected to 127.0.0.1 (127.0.0.1) port 9133 (#0)
> GET /auth/request_nonce HTTP/1.1
> Host: 127.0.0.1:9133
> User-Agent: curl/7.84.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 429 Too Many Requests
< Content-Type: application/xml
< Date: Wed, 20 Sep 2023 02:41:13 GMT
< Content-Length: 97
<
* Connection #0 to host 127.0.0.1 left intact
<Error><Code>960001</Code><Message>too many requests, please try it again later</Message></Error>%
```
* add a new error code
* update error code's readme doc
> fix: add xml response for rate limit error

- modular/gater/helper_test.go
- modular/gater/object_handler.go
- modular/gater/object_handler_test.go
- modular/metadata/metadata_bucket_service.go
- modular/metadata/metadata_object_service.go
- modular/metadata/metadata_permission_service.go
verify permission 500 code and update UT
includes these Verify Permission senarios:
1. bucket not found -> 404
2. object not found -> 404
3. invalid bucket name -> 400
4. AccAddressFromHexUnsafe(operator) -> 400
```
failed to send verify permission rpc, error: rpc error: code = Unknown desc = the specified bucket does not exist
```
N/A
* verify permission 500 code and update UT
> fix: verify permission 500 code and update UT

- modular/gater/metadata_handler.go
- store/bsdb/object.go
fix list objects by gvg sql bug
To avoid SQL query length exceeding the server's max_allowed_packet size, we can add a simple check mechanism. One way is to keep track of the query string's length and break out of the loop if it gets too close to the limit.
```
client failed to list objects by gvg id, 
error: rpc error: code = Unknown desc = Error 1436 (HY000): 
Thread stack overrun: 242207 bytes used of a 262144 byte stack, and 20000 bytes needed.  Use &#39;mysqld --thread_stack=#&#39; to specify a bigger stack.
```
N/A
* fix list objects by gvg sql bug
> fix: list objects by gvg sql bug

- CHANGELOG.md
- base/types/gfsptask/upload.go
- go.mod
This release contains 1 bugfix.
BUGFIX
* [#1171](https://github.com/bnb-chain/greenfield-storage-provider/pull/1171) fix: fix init the NotAvailableSpIdx
N/A
* N/A
> release: release for v0.2.6-hf.2

- CHANGELOG.md
- go.mod
- go.sum
- test/e2e/spworkflow/e2e_test.sh
release: draft release for v1.0.0
NO changes since last release v0.2.6-hf.2, but make it as the first official version for the main-net deployment
N/A
* N/A
> docs: release: draft release for v1.0.0

- CHANGELOG.md
- go.mod
- go.sum
- test/e2e/spworkflow/e2e_test.sh
release: release for v1.0.0
NO changes since last release v0.2.6-hf.2, but make it as the first official version for the main-net deployment
N/A
* N/A
> release: release for v1.0.0

- modular/gater/router.go
- modular/metadata/metadata_bucket_service.go
- store/bsdb/global_virtual_group_family.go
replace record not found with empty array
```
failed to get user buckets, error: rpc error: code = Unknown desc = record not found
```
N/A
* replace record not found with empty array
> fix: replace record not found with empty array

- .github/workflows/docker-develop.yml
- modular/gater/admin_handler.go
- modular/gater/admin_handler_test.go
- modular/gater/const.go
- modular/gater/router.go
- modular/gater/router_test.go
Add challenge v2 API to avoid piece hash HTTP header too large.
Components such as nginx can disconnect because the response header is too large, and users receive a 502 HTTP status code.
N/A.
* Gateway add new challenge API v2.
> fix: add challenge v2 api to avoid piece hash http header too large

- .golangci.yml
- base/gfspapp/download_server.go
- base/gfspclient/authenticator.go
- base/gnfd/gnfd_service.go
fix time.Since called in defer, it should be used in defer func.
Golang lint error as follows:
```shell
base/gnfd/gnfd_service.go:201:66: defers: call to time.Since is not deferred (govet)
defer metrics.GnfdChainTime.WithLabelValues("query_sp").Observe(time.Since(startTime).Seconds())
```
```go
func main() {
start := time.Now()
defer fmt.Println(time.Since(start))
time.Sleep(1 * time.Second)
}
```
People unfamiliar to the intricacies of the defer statement might expect that this code will print 1s, but it prints 0s. ([See on go playground](https://go.dev/play/p/hqkdf9SVtke)).
A correct version is:
```go
func main() {
start := time.Now()
defer func() { fmt.Println(time.Since(start)) }()
time.Sleep(1 * time.Second)
}
```
N/A
* N/A
> fix: fix time.Since called in defer, it should be used in defer func

- go.mod
- go.sum
- store/bsdb/object_schema.go
Try fix slow sql by add index to update at.
There are slow sql observed in testnet, which found out to be querying a sql related with object table and order by updated at. we figures adding index to update at column would help make the sql faster.
N/A
* bsdb
> feat: add index to update at

- store/bsdb/bucket.go
fix: remove the order by clause when querying buckets for discontinuing function
The original sql 
```sql
SELECT buckets.* FROM buckets INNER JOIN global_virtual_group_families ON buckets.global_virtual_group_family_id = global_virtual_group_families.global_virtual_group_family_id WHERE global_virtual_group_families.primary_sp_id = 5 AND buckets.status = 'BUCKET_STATUS_CREATED' AND buckets.create_time < 1697955241 AND buckets.removed = false ORDER BY buckets.create_at LIMIT 500
```
has an unnecessary "ORDER BY buckets.create_at " clause which largely slows down this sql execution. 
N/A
* remove the unnecessary "order by" clause
> fix: remove the order by clause for discontinuing function

- CHANGELOG.md
This release contains 2 bugfixes and 1 feature.
FEATURES
* [#1200](https://github.com/bnb-chain/greenfield-storage-provider/pull/1200) feat: add index to update at
BUGFIXES
* [#1189](https://github.com/bnb-chain/greenfield-storage-provider/pull/1189) fix: add challenge v2 api to avoid piece hash http header too large
* [#1195](https://github.com/bnb-chain/greenfield-storage-provider/pull/1195) fix:bs job connect db bug
N/A.
N/A.
> release: prepare release for v1.0.2

- base/gfspapp/app_options.go
- pkg/metrics/metric_items.go
- pkg/metrics/metrics.go
- store/sqldb/store.go
Add golang runtime metrics, process metrics and std lib db metrics to improve availability.
Improve availability and speed to debug problems.
`curl http://localhost:24367/metrics`
```
process metrics:
process_cpu_seconds_total 7.31
process_max_fds 8192
......
golang metrics:
go_gc_duration_seconds{quantile="0"} 0
go_gc_duration_seconds{quantile="0.25"} 0
go_gc_duration_seconds{quantile="0.5"} 0
go_gc_duration_seconds{quantile="0.75"} 0
go_gc_duration_seconds{quantile="1"} 0
go_gc_duration_seconds_sum 0
go_gc_duration_seconds_count 0
go_goroutines 7
......
db metrics:
go_sql_idle_connections{db_name="spdb"} 3
go_sql_in_use_connections{db_name="spdb"} 0
......
```
* N/A
> feat: add golang runtime metrics, process metrics and std lib db metrics

- modular/manager/manage_task.go
A replicate task from manager queue might be asked by more than 1 executor. So that manager needs to check the object status from reported task and abort the it if object sealed.
* ...
> fix: abort replication task if an object sealed

- CHANGELOG.md
Prepare release for v1.0.3.
This release contains 1 bugfix.
BUGFIXES
* [#1214](https://github.com/bnb-chain/greenfield-storage-provider/pull/1214) fix: abort replication task if an object sealed
N/A.
* N/A.
> release: prepare release for v1.0.3

- go.mod
- modular/metadata/metadata_permission_service.go
- modular/metadata/metadata_permission_service_test.go
- store/bsdb/database.go
- store/bsdb/database_mock.go
- store/bsdb/permission.go
- store/bsdb/permission_schema.go
The statement expiration time has a lower priority than the Policy; if it is nil, the statement will never expire. First look at the expiration time of the Policy, if it has not expired, then look at the expiration time of the statement
N/A
N/A
* update list object policies code
> fix: list object policies meta expiration

- modular/blocksyncer/blocksyncer_options.go
fix:bucket size write DB failed
bucket size Data fails to be written to the database due to large data volume. Therefore, data needs to be written in batches
nothing
* Write bucket size data in batches
> fix:bucket size write DB failed

- modular/gater/errors.go
refine the error msg for ErrInvalidExpiryDate header and parameter
The original description misleads users to use a date format 2023-04-20 16:34:12 GMT+08:00, but our case and docs uses RFC3399 format, e.g. 2006-01-02T15:04:05Z07:00
N/A
* Change the error description without other logic code change
> fix: refine the error msg for ErrInvalidExpiryDate header and parameter

- base/gfspvgmgr/virtual_group_manager.go
the SP would check if its virtual group families are available by querying the chain before assigning VGF to a bucket. It should continue picking a VGF regardless of RPC error.  
* ...
> fix: sp should resume picking VGF regardless of RPC error

- base/gfspconfig/config.go
- base/gfspvgmgr/sp_freeze_pool.go
- base/gfspvgmgr/types.go
- base/gfspvgmgr/virtual_group_manager.go
- base/gfspvgmgr/virtual_group_manager_test.go
- core/vgmgr/virtual_group_manager.go
- deployment/localup/localup.sh
- docs/run-book/config/config_template.toml
- modular/manager/bucket_migrate_scheduler.go
- modular/manager/manage_task.go
- modular/manager/manager.go
- modular/manager/manager_options.go
1. Secondary SP in blacklist would not be picked for picking VGF.
2. Secondary SP  in blacklist would not be picked for creating GVG.
3.  GVG in blacklist would not be picked for replication. 
* ...
> fix: add config sp blacklist

- modular/blocksyncer/blocksyncer_options.go
- modular/blocksyncer/database/bucket.go
- modular/blocksyncer/modules/bucket/module.go
- store/bsdb/const.go
- store/bsdb/data_migration_record.go
- store/bsdb/data_migration_record_schema.go
- store/bsdb/data_migration_record_schema_test.go
- store/bsdb/data_migration_record_test.go
- store/bsdb/database.go
- store/bsdb/database_mock.go
fix the bucket size logic
Fix the bucket size calculation logic
nothing
* Modified the SQL
> feat: add a DataMigrationRecord table to save the process record for data migration tasks

- modular/executor/execute_replicate.go
Set a timeout for calls to secondary SP, currently it is not config and the response from secondary SP might take over 2 min. This would block the executor to handle tasks. And if the Manager server can not receive a response from the executor, task will be dispatch which would cause duplicate task. 
* ...
> fix: add timeout for RPC calls to Secondary SP

- base/gfspvgmgr/virtual_group_manager.go
- modular/executor/execute_replicate.go
this pr cherry-picks 2 fixes into master.
1. https://github.com/bnb-chain/greenfield-storage-provider/pull/1229 fix: sp should resume picking VGF regardless of RPC error
2. https://github.com/bnb-chain/greenfield-storage-provider/pull/1239 fix: add timeout for RPC calls to Secondary SP
* ...
> release: prepare v1.0.5

- CHANGELOG.md
Prepare release for v1.1.0
FEATURES
* [#1240](https://github.com/bnb-chain/greenfield-storage-provider/pull/1240) feat: add a DataMigrationRecord table to save the process record for data migration tasks
* [#1218](https://github.com/bnb-chain/greenfield-storage-provider/pull/1218) feat: add sp health for pick sp
* [#1237](https://github.com/bnb-chain/greenfield-storage-provider/pull/1237) feat: signer module adds metrics for each rpc interface
* [#1227](https://github.com/bnb-chain/greenfield-storage-provider/pull/1227) feat: add reject bucket migration
* [#1224](https://github.com/bnb-chain/greenfield-storage-provider/pull/1224) feat: add gnfd cmd to query sq incomes
* [#1223](https://github.com/bnb-chain/greenfield-storage-provider/pull/1223) feat: update storage size for bucket apis
* …
> release: prepare release for v1.1.0

- modular/gater/metadata_handler_test.go
- modular/metadata/metadata_object_service.go
- modular/metadata/metadata_object_service_test.go
- modular/metadata/types/metadata_types.go
fix: fix panic when xml marshal nil objects
Xmlmarshal would fail into panic if the queried object doesn't exist.  This fix will solve this issue.
```
curl --location 'http://127.0.0.1:9133/?groups-query=null&ids=12323412341234'
```
```xml
<GfSpListGroupsByIDsResponse>
<GroupEntry>
<Id>12323412341234</Id>
</GroupEntry>
</GfSpListGroupsByIDsResponse>
```
* add more nil checking 
* add more ut
N/A
> fix: fix panic when xml marshal nil objects

- .github/workflows/docker-develop.yml
This PR switches the Dockerfile being used to `Dockerfile.distroless` for GitHub action 
To improve security within Kubernetes environment, it is recommended to use distroless image to prevent potential attack.
N/A
Use `Dockerfile.distroless` to build. It has already been used in `signer`.
The debugging will be harder, because after the change we cannot `exec into` the pods directly any more.
> chore: switch develop image to distroless

- CHANGELOG.md
Prepare release for v1.2.2
BUGFIXES
BUGFIXES
* [#1284](https://github.com/bnb-chain/greenfield-storage-provider/pull/1284) fix: remove tags field when creating object/group/bucket
N/A.
* Add CHANGLOG for v1.2.2
> release: prepare release for v1.2.2

- modular/manager/manage_task.go
The task reported from executor brings the notAvailableSPIdx if found replication failed. It should be used to check whether secondary SP is abnormal.
* ...
* ...
> fix: replicate failed sp idx not included in local task

- .github/workflows/docker-develop.yml
- modular/gater/admin_handler.go
- modular/gater/admin_handler_test.go
- modular/gater/errors.go
- util/string.go
During the process of creating an object and getting approval, restrictions on illegal special characters were added
S3 supports, but SP does not support. Currently, all are being blocked by WAF. These objects, once created, cannot be sealed.
- `123../1.txt`
- `...barry`
- `..barry`
-`/`
- `data;DROP TABLE objects` (SQL Injection)
-`\`
- `\\`
- `\r`
- `\n`
N/A
* During the process of creating an object and getting approval, restrictions on illegal special characters were added
* QA
> feat: invalid object name

- base/gfspvgmgr/sp_freeze_pool.go
- modular/gater/admin_handler.go
- modular/gater/admin_handler_test.go
1. Secondary SP might need to wait for object meta due to latency , so that it will not report err msg back to primary SP easily.
2. Shorten the SP freeze time to 5 min. 
* ...
* ...
> fix: secondary SP might need to wait object meta due to latency

- modular/manager/recover_scheduler.go
calibrate recover objects frequency to facilitate the recover process. Due to most objects stored are in small size.
* ...
* ...
> fix: calibrate recover objects frequency

- .github/workflows/docker-develop.yml
- base/gfspconfig/config.go
- modular/blocksyncer/blocksyncer.go
- modular/blocksyncer/blocksyncer_indexer.go
- modular/blocksyncer/blocksyncer_options.go
- modular/blocksyncer/database/bucket.go
- modular/manager/recover_scheduler.go
blocksyncer sql is commit in batches
When dealing with large blocks, sql may exceed the limit length and cause an error
The number of sql committed each time is adjusted by the configuration
* Add the configuration item commit number
* sql batch commit
* sync speed
> perf: blocksyncer sql commit

- modular/gater/admin_handler.go
- modular/gater/admin_handler_test.go
- modular/gater/errors.go
- modular/gater/helper_test.go
- modular/gater/object_handler.go
- modular/gater/object_handler_test.go
- util/string.go
revert two commits for special object name handling
https://github.com/bnb-chain/greenfield-storage-provider/pull/1314
https://github.com/bnb-chain/greenfield-storage-provider/pull/1298
N/A
N/A
* revert two commits 
N/A
> fix: revert object commits

- CHANGELOG.md
Description
Draft release for v1.3.0.
Rationale
BUGFIXES
* [#1304](https://github.com/bnb-chain/greenfield-storage-provider/pull/1304) fix: fix sp unhealthy bug
* [#1311](https://github.com/bnb-chain/greenfield-storage-provider/pull/1311) fix: fix health check
FEATURES
* [#1279](https://github.com/bnb-chain/greenfield-storage-provider/pull/1279) feat: re-implementation of sp exit
* [#1312](https://github.com/bnb-chain/greenfield-storage-provider/pull/1312) perf: blocksyncer sql commit
Example
N/A.
Changes
Notable changes:
changelog
> docs: release for v1.3.0

- modular/gater/admin_handler.go
- modular/gater/admin_handler_test.go
- modular/gater/errors.go
- modular/gater/helper_test.go
- modular/gater/object_handler.go
- modular/gater/object_handler_test.go
- util/string.go
re-apply two commits for special object name handling
https://github.com/bnb-chain/greenfield-storage-provider/pull/1314
https://github.com/bnb-chain/greenfield-storage-provider/pull/1298
N/A
N/A
* re-apply two commits 
N/A
> fix: re-apply object commits

- go.mod
- modular/gater/object_handler_test.go
- modular/metadata/metadata_query_service.go
- modular/metadata/metadata_query_service_test.go
- modular/uploader/upload_task.go
- modular/uploader/uploader_task_test.go
- store/types/store.go
- store/types/store_test.go
Not allowed to upload piece or object for an object id which had already been fully uploaded before
Users might repeatedly upload pieces for a given object which had already been fully uploaded before. This might be due to some kinds of user code issues. But in sp side we should not allow this. 
Before this fix, sp will override the file content in piece store, which might cause "integrity check" not matching.
N/A
* uploadTask: PreUploadObject
* uploadTask: PreResumableUploadObject
N/A
> fix: Not allow to upload piece/object for a fully-uploaded object

- modular/metadata/metadata_object_service.go
- modular/metadata/metadata_object_service_test.go
return 500 when bucket is deleted
N/A
* add UT
* fix error code
* QA
> fix: 500 error code when bucket is deleted

- modular/manager/migrate_service.go
- modular/metadata/metadata_bucket_service.go
- modular/metadata/metadata_bucket_service_test.go
- modular/metadata/metadata_test.go
- store/sqldb/traffic.go
- store/sqldb/traffic_test.go
fix: let bucket migration be able to start without a pre-read of bucket content
Previously, the bucket migration could not be started as long as the bucket objects have never been read before, due to defect happens during GfSpGetLatestBucketReadQuota
N/A
* Make it be able to return gorm.ErrRecordNotFound when reading traffic table if there is no corresponding record.
* Backfill the GfSpBucketQuotaInfo object when no record is found when reading traffic
* ut
N/A
> fix: let bucket migration be able to start without a pre-read of bucket content

- modular/gater/migrate_handler.go
- modular/metadata/metadata_bucket_service.go
- modular/metadata/metadata_bucket_service_test.go
fix: correct the bucket quota formula when pre-check in bucket migration
The original comparison expression did not take the "ChargedQuotaSize" and "ReadConsumedSize" into account
N/A
N/A
N/A
> fix: correct the bucket quota formula when pre-check in bucket migration

- base/types/gfsptask/recovery.go
- base/types/gfsptask/task_key.go
- base/types/gfsptask/task_key_test.go
- modular/manager/recover_scheduler.go
exclude timestamp from recover piece key to avoid duplicate request enqueued. 
* ...
* ...
> fix: exclude timestamp from recover piece key

- CHANGELOG.md
BUGFIXES
* [#1347](https://github.com/bnb-chain/greenfield-storage-provider/pull/1347)  fix: init the bucket traffic when NotifyPreMigrateBucketAndDeductQuota
* [#1343](https://github.com/bnb-chain/greenfield-storage-provider/pull/1343)  fix: correct the bucket quota formula when pre-check in bucket migration
* [#1341](https://github.com/bnb-chain/greenfield-storage-provider/pull/1341)  fix: let bucket migration be able to start without a pre-read of bucket content
* [#1333](https://github.com/bnb-chain/greenfield-storage-provider/pull/1333)  fix: Not allow to upload piece/object for a fully-uploaded object 
* [#1314](https://github.com/bnb-chain/greenfield-storage-provider/pull/1314)  fix: special object download issue 
* [#1315](https://github.com/bnb-chain/greenfield-storage-provider/pu …
> docs: release for v1.4.0

- CHANGELOG.md
BUGFIXES
* [#1344](https://github.com/bnb-chain/greenfield-storage-provider/pull/1344)  fix: exclude timestamp from recovery piece key to avoid duplicate requests
* [#1342](https://github.com/bnb-chain/greenfield-storage-provider/pull/1342)  fix: Upload_Done task loaded from DB does not have GVG info
* [#1336](https://github.com/bnb-chain/greenfield-storage-provider/pull/1336)  fix: 500 error code when bucket is deleted
* [#1334](https://github.com/bnb-chain/greenfield-storage-provider/pull/1334)  fix: gc object retry due to deleted bucket
FEATURES
* [#1337](https://github.com/bnb-chain/greenfield-storage-provider/pull/1337)  feat: atomic object update 
* [#1345](https://github.com/bnb-chain/greenfield-storage-provider/pull/1345)  feat: update gvg save logic
* …
> docs: release for v1.5.0

- go.mod
- go.sum
- modular/blocksyncer/blocksyncer_options.go
> fix: bs statistic

- CHANGELOG.md
BUGFIXES
* [#1394](https://github.com/bnb-chain/greenfield-storage-provider/pull/1394)  fix: pick new gvg when retry failed replicate piece task
* [#1391](https://github.com/bnb-chain/greenfield-storage-provider/pull/1391)  fix: check if it is AgentUploadTask
* [#1390](https://github.com/bnb-chain/greenfield-storage-provider/pull/1390)  fix: delegate upload param check
* [#1389](https://github.com/bnb-chain/greenfield-storage-provider/pull/1389)  fix: delegate upload param check
* [#1387](https://github.com/bnb-chain/greenfield-storage-provider/pull/1387)  fix: upgrade deps for fixing vulnerabilities
* [#1386](https://github.com/bnb-chain/greenfield-storage-provider/pull/1386)  fix: check if BucketExtraInfo is nil
* [#1384](https://github.com/bnb-chain/greenfield-storage-provider/pull/1384 …
> docs: release for v1.7.0

- modular/manager/task_retry_scheduler.go
fix: use exponential backoff for task retry policy
We will avoid too many task retry execution, we use a exponential backoff policy
N/A
Create 3 maps to store the backoff data for the following 3 retry task types
* replicateTask
* sealTask
* rejectUnsealTask
N/A
>  fix: use exponential backoff for task retry policy

- base/errors.md
- base/gfspclient/client.go
- base/gfspclient/gater.go
- modular/approver/approve_task.go
fix: refine error code for bucket migration
During bucket migration, it could happens that users's buckets do not have enough quota or the bucket is still in gc or in migrating. So for such cases,  the current 500 error code is not reasonable. This pR changes the error cod to 406.
N/A
N/A
N/A
>  fix: refine error code for bucket migration

- modular/gater/admin_handler.go
fix: change replicate failure error code to 404 when object is not found
During replicating, the object could possibly be removed by users, so a 404 will be reasonable then 500
N/A
N/A
N/A
> fix: change replicate failure error code to 404 when object is not found

- modular/gater/admin_handler.go
- modular/gater/bucket_handler.go
- modular/gater/migrate_handler.go
- modular/gater/object_handler.go
- modular/gater/query_util.go
Add detailed logs including bucket_name, obejct_name etc. to 4 kinds of special logs that does not have context.
There are 4 special kinds of logs that need to record the detail, therefore had to register the log in gfsperrors at the time of invocation. These logs does not have context come with them, making debug difficult. Additional logs about bucket name and object names can provide more details.
original:
err = ErrConsensusWithDetail("failed to get object info from consensus,  error: " + err.Error())
updated:
err = ErrConsensusWithDetail("failed to get object info from consensus, object_name: " +objectInfo.objectName + ", bucket_name: " + objectInfo.bucketName + ",  error: " + err.Error())
* adding more logs to gater module
> feat: add detailed logs for special customized logs

- base/gfspvgmgr/virtual_group_manager.go
- pkg/metrics/metric_items.go
fix: check sp health retry
```
defaultSPCheckTimeout               = 1 * time.Minute
defaultSPHealthCheckerInterval      = 10 * time.Second
defaultSPHealthCheckerRetryInterval = 1 * time.Second
defaultSPHealthCheckerMaxRetries    = 5
```
N/A
* fix: check sp health retry
* N/A
> fix: check sp health retry

- modular/receiver/receive_task.go
- modular/receiver/receive_task_test.go
receice interface idempotent processing
> perf: receive done

- modular/gater/errors.go
- modular/gater/object_handler.go
replace error code from 500 to 404 when object is not found
```
"gater/object_handler.go:437","msg":"HttpStatusCode[500] action[GetObject] 
\"inner_code\":55001,\"description\":\"failed to get object info from consensus, 
error:rpc error: code = Unknown desc = No such object: unknown request\"
```
* replace error code from 500 to 404 when object is not found
* QA
> fix: no such object error code

- Makefile
- README.md
- cmd/command/bs_data_migration/v1.0.1/fix_payment.go
- cmd/command/query.go
- core/piecestore/piecestore.go
- core/piecestore/piecestore_mock.go
- modular/executor/execute_gc.go
- modular/executor/executor_task_test.go
- store/piecestore/client/piece_store_client.go
- store/piecestore/piece/api.go
- store/piecestore/piece/api_mock.go
- store/piecestore/storage/disk_file.go
- store/piecestore/storage/interface.go
- store/piecestore/storage/interface_mock.go
- store/piecestore/storage/memory.go
- store/piecestore/storage/oss.go
- store/piecestore/storage/s3.go
- store/piecestore/storage/sharding.go
- store/sqldb/object_integrity.go
Currently in sp, if an object is deleted within the same tx as its local virtual group (lvg), the async GC Task will have issue finding its secondary sps, as this info is only available by using logic objectId -> lvg -> gvg -> secondary sps.
In this case, it used to be that the data in secondary sp's data storage will not be removed. Now updating logic for all sps to check for files that have prefix related to the object (as "e{objectid}_"), and remove all related files.
Update logic of GC 
https://testnet.greenfieldscan.com/tx/0x2a34610146b15f60728e79b96181dc2af60825578822f70b913348b6cb8bed28
This link is an example of object & lvg in the same tx.
* GC Task
* new data storage methods
* GC Task
> feat: fix gc objects

- CHANGELOG.md
BUGFIXES
* [#1435](https://github.com/bnb-chain/greenfield-storage-provider/pull/1435) fix: gc objects
> docs: release v1.10.0
